### ISSUE TITLE
[ FF8 ] splash screen skip

### ISSUE THREAD

**Issue by MaKiPL** [julianxhokaxhiu/FFNx#102]
Steam release had a functionality to skip the splash screens (2000 release didn't)
so we have some options:
1. Bring back skip splash functionality
2. Add a config option to skip all splashes automatically (I did that on 2000, I'll try to dig out how I did that)

**Comment by julianxhokaxhiu** [comment]
Thanks, I'll ping you when I'll start to work on this. If you can figure out a way to accomplish this in the meanwhile, feel free to create a PR :) I'll be happy to work with you on this.

**Comment by myst6re** [comment]
I added a patch in #142 to skip the Squaresoft logo and the intro credits. The first movie remains, you can skip it with the Ctrl+S cheat.
