### ISSUE TITLE
[ FF7 ] Barret's eyebrow not loading

### ISSUE THREAD

**Issue by KuraudoXS** [julianxhokaxhiu/FFNx#107]
![Screen Shot 2020-10-04 at 10 07 48 PM](https://user-images.githubusercontent.com/9687549/95023489-5ff5d080-068e-11eb-928a-5ca0888c0bf2.png)
Barret "bad texture" eyebrow PC (8:26): https://youtu.be/vixZODADlPw?t=504

![Screen Shot 2020-10-04 at 10 08 14 PM](https://user-images.githubusercontent.com/9687549/95023493-671cde80-068e-11eb-82ae-eea68d894a9b.png)
Barret original eyebrow PSX (57:38): https://youtu.be/yiRgmBpAfNk?t=3454

Could be another "not loaded texture" thing.

**Comment by julianxhokaxhiu** [comment]
It seems the texture is bound correctly, although it's not identical to the one on the PSX. If you want to fix it you'll need to replace it externally.

![image](https://user-images.githubusercontent.com/1237070/95209781-048d2500-07eb-11eb-88ef-581606cd17b9.png)

As we can't do much code-wise I'll close this issue :)

Thanks for the report!

**Comment by KuraudoXS** [comment]
> 
> 
> It seems the texture is bound correctly, although it's not identical to the one on the PSX. If you want to fix it you'll need to replace it externally.
> 
> ![image](https://user-images.githubusercontent.com/1237070/95210774-21762800-07ec-11eb-8aa5-743d55b55108.png)
> 
> As we can't do much code-wise I'll close this issue :)
> 
> Thanks for the report!

No issue. Just want to mention that the texture which is bound correctly might be Cloud's eyebrow.

**Comment by julianxhokaxhiu** [comment]
Maybe it's a bug in the model file?

**Comment by Kaldarasha** [comment]
This is a bug with ff7.exe. Some models, actually every model which doesn't belong to the main cast, does use clouds closed eyes. While that is Barrett in that scene, that model isn't known by the game as main character, so it use Cloud's eyes instead.

**Comment by KuraudoXS** [comment]
@julianxhokaxhiu @tangtang95 

After the great achievement by the FFNx team in fixing the Red XIII eye issue. 
If this is still relevant: I wanted to leave here the last updates.

From the Discord:
vertex2995: "Is that a different model of Barret?"
L@Zar0: "That is the idea. When the game detects the model FQCB, that it assigns the same value as ACGD."
vertex2995: "Then it's probably really easy to fix. Just rewrite that function that returns the eye texture index."
TrueOdin: "I think we'll need to go down that path as well. I'll add the code to replace the call so we can control it
and later extend or fix whatever needs a fix."
vertex2995: "Might be better to just hardcode the strings instead of taking it from ff7.exe. Also the second part (else part) is useless (I think it was for debug mode.)"
TrueOdin: "I'll let you know when I'll get on it."


Here below the known scripted occasions:
1) Aerith's eye texture 3 used when she is laughing during Cloud's dream after the Temple of Ancients.
2) Barret's eye texture 4 is used during his flashback in Corel's Prison, when Dyne is falling.
All other eye textures, which would give a different facial expression for the characters, aren't used.
The PC version only includes eyes textures 1 and 2, so the scenes above are not displayed properly:
-In Cloud's dream after the Temple of Ancients, Aerith's eye texture 1 (regular open eyes) is used when she is laughing.
-In Barret's flashback, oddly enough, Cloud's eye number 2 (closed eyes) is used on Barret's model.

Each playable character also includes two mouth textures (closed and open variations). Only Cid's and Tifa's mouth textures are used in the PlayStation version, and only in two scripted occasions:
3) Cid's mouth texture 2 (open mouth) is used in the scene where he is with Cloud in Gold Saucer's Round Square.
4) Tifa's mouth texture 1 (closed mouth) is used when she is talking to Cloud under the Highwind at the end of Disc 2." 

Source: https://tcrf.net/Final_Fantasy_VII
Eye Texture picture: https://pbs.twimg.com/media/FYjtVXnWIAEcmt8.png
