### ISSUE TITLE
[ FF8 ] Cheat code "battle mode" does not work

### ISSUE THREAD

**Issue by myst6re** [julianxhokaxhiu/FFNx#120]
When I disable battle encounters, you can still fight in the WorldMap.

**Comment by julianxhokaxhiu** [comment]
Unfortunately that cheat code is known to not work on FF8 ( see https://github.com/julianxhokaxhiu/FFNx#battle-mode-toggle ) but I'd be really happy to find a way to disable those somehow. If anyone has a lead on what to patch in memory I'll be happy to streamline it across all languages :)

**Comment by myst6re** [comment]
It seems to work now, isn't it?

**Comment by julianxhokaxhiu** [comment]
Oh yes, you're right! Time to close this one, thanks :D
