### ISSUE TITLE
[ FF7 ] Audio Codec Mix

### ISSUE THREAD

**Issue by satsukiyatoshi** [julianxhokaxhiu/FFNx#129]
It would be cool to be able to use psf for some music and ogg or flac for other musics
So anyone can make custom mix from differents source
A "simple" way to interface it with the config file would be to set up a file priority
For exemple : audio_priority = "psf,flac,ogg"

So ingame if a psf music is found it's using it, if no psf found, it's search for an ogg one ....

Thanks

**Comment by myst6re** [comment]
We can do it easily now with toml, I'll make a PR

**Comment by julianxhokaxhiu** [comment]
Fixed by #132
