### ISSUE TITLE
[ FF8 ] Movie Skip can block the game progression

### ISSUE THREAD

**Issue by myst6re** [julianxhokaxhiu/FFNx#143]
Sometimes field scripts use the current movie playing position to trigger new actions.
For example Deling City parade, when Squall and Irvine needs to go to the right in the crowd.

It appears that the current movie frame variable is not updated when a movie skip occurs.

![2020-12-23 02_24_40-field fs - Deling 0 10 1b](https://user-images.githubusercontent.com/8015696/102948318-07ccae80-44c6-11eb-9488-1f0e860d8b4d.png)

**Comment by julianxhokaxhiu** [comment]
I think it's very related to what happens in FF7. What we can do instead for now, as a workaround, is not allowing the fmv skip to trigger on certain fields. If you know how to get the current field ID, we can use that to do a proper IF like this one: https://github.com/julianxhokaxhiu/FFNx/blob/master/src/ff7/misc.cpp#L273

**Comment by myst6re** [comment]
Here is a list of potentially impacted maps:
 - testbl3 (92)
 - bg2f_11 (138)
 - bg2f_21 (140)
 - bg2f_31 (144)
 - bgbtl_1 (152)
 - bggate6a (164)
 - bgkote_4 (187)
 - bgmd4_2 (208)
 - bgroad_6 (229)
 - bgroom_3 (233)
 - bgsido_3 (252)
 - bgsido_4 (253)
 - bgsido_8 (258)
 - doani3_1 (311)
 - ...
Okay no... there's too much!

**Comment by myst6re** [comment]
#148
