### ISSUE TITLE
I can't load a save file. Game crashes

### ISSUE THREAD

**Issue by llLanni** [julianxhokaxhiu/FFNx#152]
When i try to load a save file a window pops up saying:

"Oops! Something very bad happened.

Wrote emergency save to save/crash.ff7 dir.

Please provide a copy of those files along with FFNx.LOG
when reporting this error at 
https://github.com/julianxhokaxhiu/FFNx/issues"

Help me please. I'm frustrated.

**Comment by eve-atum** [comment]
Make sure the "60fps" option in the Animations mod is disabled (or better yet, get rid of the animations mod entirely).  Past that, we can't suggest anything without seeing the log.

**Comment by llLanni** [comment]
> Make sure the "60fps" option in the Animations mod is disabled (or better yet, get rid of the animations mod entirely). Past that, we can't suggest anything without seeing the log.

The animations mod was the problem indeed. Thank you! How can i show you the log?

**Comment by eve-atum** [comment]
Well, since we've identified that the animations mod was the problem, there's no need for the log ;)  Enjoy the game!

**Comment by llLanni** [comment]
> Well, since we've identified that the animations mod was the problem, there's no need for the log ;) Enjoy the game!
The problem came back. This time when i press play in 7th heaven that window shows up right away. I deleted the animations mod but this doesn't seem the problem anymore :(

**Comment by llLanni** [comment]
> Well, since we've identified that the animations mod was the problem, there's no need for the log ;) Enjoy the game!

The problem came back. This time when i press play in 7th heaven that window shows up right away. I deleted the animations mod but this doesn't seem the cause of the problem anymore :(

**Comment by julianxhokaxhiu** [comment]
Please post and talk about 7th issues on the forum, this repository is not related to 7th ( despite 7th using FFNx ). Thank you :)
