### ISSUE TITLE
[ FF8 ] Animation FPS drop in few movies with external_movies on

### ISSUE THREAD

**Issue by myst6re** [julianxhokaxhiu/FFNx#159]
After BGU transformation, there is one moment when character animations are really slow. I think it is related to external_movies, because this seems to not happen in FF8 2000.

https://www.twitch.tv/videos/900625691?t=01h20m38s

[slot1_save23.zip](https://github.com/julianxhokaxhiu/FFNx/files/5936646/slot1_save23.zip)

**Comment by julianxhokaxhiu** [comment]
Nice catch! I labelled this issue as help wanted in case someone else wants to jump first on this issue, meanwhile I'll try to investigate and check if I can find the issue. Thanks :)

**Comment by myst6re** [comment]
Thanks again!
