### ISSUE TITLE
[ FF7 ] No music in the world map after a game over.

### ISSUE THREAD

**Issue by daedrixxx2** [julianxhokaxhiu/FFNx#202]
After a Game Over, if "external_music_resume" is set to "true", when reloading the game there'll be no music in the world map (didn't try if it happens in fields too). After a battle, or entering a town, music restarts normally.
This bug doesn't happen if "external_music_resume" is set to "false".

**Comment by julianxhokaxhiu** [comment]
@myst6re Would you be able to look at this one? Thank you!

**Comment by myst6re** [comment]
Yes assign this issue to me please

**Comment by julianxhokaxhiu** [comment]
@daedrixxx2 can you please try the latest canary and report back? Thank you

**Comment by daedrixxx2** [comment]
The bug has been resolved :)

And I'm pleased to learn that the issue with the music resume feature on known areas has been resolved as well :D

Good work everyone. Thank you 👍

**Comment by julianxhokaxhiu** [comment]
Thanks for testing, glad everything was sorted out :) Enjoy!
