### ISSUE TITLE
[ GAME ] ISSUE - Fatal crash on entering Mako reactor (repeated)

### ISSUE THREAD

**Issue by john-savepoint** [julianxhokaxhiu/FFNx#204]
**Describe the bug**
Game has major consistent crash when entering the Mako reactor at the start of the game. 

**To Reproduce**
It reoccurs when you enter the reactor from the big T walkway (similar to what you fight Airbuster on later) and is trying to load in the first room where Barret is starts talking about Mako and the planet.

**Expected behavior**
This is a total crash, expect it to play

**Screenshots**
[crash.zip](https://github.com/julianxhokaxhiu/FFNx/files/6031763/crash.zip)

**GPU (please complete the following information):**
- Brand : Intel UHD Graphics 620
- Driver Version :  27.20.100.8935

**Additional context**
Game says to post crash log here. I have attached in a zip file
Mods Installed:
-New Threat Mod v2.0.94
-Final Fantasy 7 Steam version 1.0.9
-Satsuki Yatoshi Upscale Mod Version 5.21 release

**Comment by julianxhokaxhiu** [comment]
No support for 7th Heaven will be provided here. Please use the relative dedicated Discord support channels.
