### ISSUE TITLE
[ FF7 ] Using External SFX makes the game crash.

### ISSUE THREAD

**Issue by daedrixxx2** [julianxhokaxhiu/FFNx#209]
Hello. It looks like setting "use_external_sfx" to "true" makes the game crash.
As soon as I fight some battles in the world map the game crashes. It can crash in the after-battle items found screens or in a field screen.
I even tried deleting any sfx inside the sfx folder, making the game mute apart from the music, but as long as the external sfx are on, after some battles, the game hangs. The music continues, but the game is frozen and I have to press the windows key on the keyboard to close the game.
If the external sfx are off no crashes happen.

**Comment by julianxhokaxhiu** [comment]
Please provide some more context:
- Are you using the latest canary? If not, please do so.
- Please provide some logs

Thank you

**Comment by daedrixxx2** [comment]
[FFNx.log](https://github.com/julianxhokaxhiu/FFNx/files/6091615/FFNx.log)

This is with the latest canary ver. 207. It happened the same with ver. 206.

The message I get when it crashes is simply "FF7 has stopped responding". It's not one of those crashes where it says to upload the log file, so I don't think there's anything useful written in the log.

**Comment by julianxhokaxhiu** [comment]
> [FFNx.log](https://github.com/julianxhokaxhiu/FFNx/files/6091615/FFNx.log)
> 
> This is with the latest canary ver. 207. It happened the same with ver. 206.
> 
> The message I get when it crashes is simply "FF7 has stopped responding". It's not one of those crashes where it says to upload the log file, so I don't think there's anything useful written in the log.

Indeed there's no crash stacktrace so unfortunately I have no idea how to tackle this.

> This happens with ogg files, specifically those ripped from "The Reunion" mod. Those are ripped from the PSX version.
> I chose those because they're the only vanilla sfx I could find. Bonez's sfx are not vanilla, and not using the external sfx functionality leads to the same old sfx bugs the PC version has, like the sfx in the Lifestream sequence with Tifa not being played correctly.

There's no support for Reunion files sorry. You can use one of the many other mods battle tested on FFNx.

> BTW does FFNx support wav files? I tried ripping the PC version's own sfx, and even after changing the format to "wav" in the config the game crashes as soon as it tries to play a sfx, this time the error message says to upload the log, and a crash.ff7 save is created.

It should, but if it crashes please make sure to upload that log file with a valid stacktrace in it.

**Comment by daedrixxx2** [comment]
> It should, but if it crashes please make sure to upload that log file with a valid stacktrace in it.

I hope this suffices.

[FFNx.log](https://github.com/julianxhokaxhiu/FFNx/files/6095621/FFNx.log)

> There's no support for Reunion files sorry. You can use one of the many other mods battle tested on FFNx.

Do you know of any sfx pack with the vanilla sfx that works with FFNx? If not I could open a new issue about fixing that scene with Tifa in the Lifestream by modifying the flevel as you mentioned. I'd do it myself if I knew how...

**Comment by julianxhokaxhiu** [comment]
> I hope this suffices.
> 
> [FFNx.log](https://github.com/julianxhokaxhiu/FFNx/files/6095621/FFNx.log)
 >
> Do you know of any sfx pack with the vanilla sfx that works with FFNx? If not I could open a new issue about fixing that scene with Tifa in the Lifestream by modifying the flevel as you mentioned. I'd do it myself if I knew how...

Not that I am aware of. What did you use to extract those WAV files? Thanks for the log though, but I would need either the files or what did you use to extract them to test this scenario. I'll try with my own FF7SND version too, just to test if it's about WAV files or maybe the kind of files your using.

**Comment by daedrixxx2** [comment]
I used a sfx (wav) pack found in a sfx forum.  And with it, it crashes immediately with the log I sent you.

Next I tried extracting my own audio.fmt with cosmo095c. Just a few (wav) files, and while they do work, the game crashes after a few battles the same way it crashed with the sfx ripped from "The Reunion" (every 750+ ogg file), just telling me "FF7.exe stopped working", with no useful log.

**Comment by julianxhokaxhiu** [comment]
So I personally tested the WAV scenario and works fine extracting them from the `audio.dat` using https://github.com/julianxhokaxhiu/FF7SND/releases

If the driver crashes with those files, it means something is odd on those files you're using.

Closing this issue as it is not an actual issue :)

Thanks and cheers!
