### ISSUE TITLE
[ FF7 ] Game crash when trying to save

### ISSUE THREAD

**Issue by tekkensora** [julianxhokaxhiu/FFNx#215]
**Describe the bug**
I tried many times to start a new game and save on the first save spot of the game, did re-install a few times on version 5.26 and even played on 5.21 to save on all the 10 options in case that fixed the problem, seems like using 5.21 works fine but 5.26 always gives me the following error, not saving the game at all and crashing afterwards, ofc i'm using the all-in-one installer for steam and not the 7th Heaven, while you check on this I'll play on 5.21 without the transparent windows option because the mod looks so good I want to play it no matter what! (thanks for your time)

**To Reproduce**

1. Install the game on steam
2. Install 5.21 then install 5.26
3. Start the game with every setting on the top (no 3d models) then anisotropic, v-sync, 16/9 and advanced animations on the right settings, (also "auto graphic engine" gave me an error so I tried DX11, DX12 and Vulkan with same result)
4. Start a new game or load a save file
5. Select Save, then select one of the 10 options
6. See error while the bar is loading

**Expected behavior**
Obviously the game letting me open the save slots and actually saving the game

**Screenshots**
(sorry for the bad quality)
![Screenshot_1](https://user-images.githubusercontent.com/80450903/110758674-1321b180-824d-11eb-8efe-93b128973978.png)

**GPU (please complete the following information):**

- Brand: Nvidia (1060 6gb)
- Driver Version: Latest on Gforce experience (461.72)

**Additional context**
I'll upload here the crash.ff7 and the .log on a zip file
[crash-and-log.zip](https://github.com/julianxhokaxhiu/FFNx/files/6121601/crash-and-log.zip)

**Comment by satsukiyatoshi** [comment]
Could you provide the FFNx.toml file too?

**Comment by satsukiyatoshi** [comment]
Ok i've done some test and it seems to be related to not english version of steam game.
English version save well, but other lang not.
It's probably related to the change un FFNx some time ago to avoid to loose save in some crash cases.

About the "auto" engine not working i've done some test and seems i forgot to neutralise a function in my pack launcher, i'll output a corrected upadate as soon as the save function in FFNx will be corrected ^^
