### ISSUE TITLE
[ FF7 ] Tiny Bronco sound stops after first play

### ISSUE THREAD

**Issue by wturner859** [julianxhokaxhiu/FFNx#238]
**Describe the bug**
 the engine sound for the tiny bronco only plays once. if you stop moving and move again, the sound doesn't play... if you force another sound to play (like the buggy) and then come back to the tiny bronco, the sound will play once again. The same is not true for the buggy sound. it always plays as intended. Here is a link to a clip: https://clips.twitch.tv/CrunchyCrackyLegPoooound-8lQ4EugROxbyTD1q   The sound ID in question is 493 and here is the traced log

**To Reproduce**
drive tiny bronco

**Expected behavior**
continue to play regardless how many times you move.

**Screenshots**
screen of traced log in our private discord chat

**GPU (please complete the following information):**

- Brand Nvidia
- Driver Version latest canary

**Comment by julianxhokaxhiu** [comment]
A tentative patch for this issue has been pushed and a new canary is available. Please feel free to try and let me know how it goes. I hope I fixed this issue only and I didn't broke the SFX layer around.

**Comment by julianxhokaxhiu** [comment]
New patch submitted, this one has no side effects and actually fixes a logic it was supposed to be there but we forgot to implement it along the road. You'll be able to test this starting next canary :)
