### ISSUE TITLE
[ FF7 ] Foot step sound layer.

### ISSUE THREAD

**Issue by wturner859** [julianxhokaxhiu/FFNx#253]
Just an idea. a sound layer that could detect when you're on the field (or maybe the world map as well, if possible) and if you hold down the d-pad(move the character), the sound layer would play a looped foot step sound effect for as long as you hold down the button.... Could possibly even take the same logic used for the Tiny Bronco/Buggy... Bonus points for conditional sounds based on field-id; as in different sounding foot steps for different environments (like snow, concrete, sand, etc.)

### Motivation

The cherry on top of the cherry. The last piece of the sfx puzzle.

**Comment by julianxhokaxhiu** [comment]
Canary is now out to be tested. Let me know how it goes :)

**Comment by julianxhokaxhiu** [comment]
Added some minor improvements.
