### ISSUE TITLE
[ AUDIO ] ogg loops with vgstream not working well. (CANARY)

### ISSUE THREAD

**Issue by TurBoss** [julianxhokaxhiu/FFNx#261]
some song loops fail to load with label "LOOP_START" , "LOOP_END" and "LOOP_LENGTH"

some other song loop fine

**To Reproduce**
create a looped ogg with audacity

1. set "LOOP_START"

**Expected behavior**
song playing in loops forever

**Additional context**
vg stream from ffnx lastest from 7heaven canary channel

Thanks

**Comment by julianxhokaxhiu** [comment]
Hey, I doubt it has an issue as the code is [upstream in VGMStream](https://github.com/vgmstream/vgmstream/blob/becac80999af1a75bb0d8710d6f4c29918bce97a/src/meta/ffmpeg.c#L178) and there are other mods using this feature currently.

Please consider using `LoopStart`, `LoopEnd` and `LoopLength` instead.

Thank you!
