### ISSUE TITLE
[ FF7 ] (Recently Introduced) Layered battle sounds only playing 1 layer

### ISSUE THREAD

**Issue by wturner859** [julianxhokaxhiu/FFNx#263]
**Describe the bug**
Battle sounds that have more than 1 sound playing simultaneously (eg. Comet (sound id 76+77)) are now only playing 1 sound (eg. just 77). This is a recent bug I THINK introduced in 1.9.0.79, But I can't confirm that. I can only confirm that reverting to 1.9.0.54 (latest release I have pre .79) fixes the issue.
I thought it was because it was trying to play both sounds on channel 6... but the .54 log shows the same thing and it plays them fine.
Biggest difference between the 2 logs is a 
[00001202] TRACE: NxAudioEngine::unloadSFXChannel: channel=6
between the sounds

EDIT: Same thing is happening with all summons

Considering I believe you put in that unloadsfxchannel in there to fix the issue with the reactor sounds, it may not be necessary to have that on channels 5 and 6 which are just for battle and summons and have a lot of layering sounds which is apparently causing problems. I'm only guessing, though.

I'm attaching both logs
[1.9.0.54log.txt](https://github.com/julianxhokaxhiu/FFNx/files/6759469/1.9.0.54log.txt) < works
[1.9.0.83log.txt](https://github.com/julianxhokaxhiu/FFNx/files/6759470/1.9.0.83log.txt) < doesn't work

**To Reproduce**
cast Comet or Freeze or any magic that has layered sounds or a summon.

**Expected behavior**
Play all sounds

**Comment by julianxhokaxhiu** [comment]
You're right sorry, I completely forgot that channel 6 lazy unloads effects. When i was working on the footsteps part I thought I could uniform that layer but unfortunately is not true. Nevertheless now I brought back that logic only for channel 6, so anything about that will continue to work as expected.

For you this means you should get both footsteps and summons ( or anything using channel 6 ) to correctly play as expected. Let me know how it goes!
