### ISSUE TITLE
[ FF7 ] Black flashing on DX11 is back and DX12 is crashing on battle with .109

### ISSUE THREAD

**Issue by wturner859** [julianxhokaxhiu/FFNx#267]
**Describe the bug**
Starting in .109, when using Cetra, the previously remedied black flashing has returned when using DX11... On DX12, when using Cetra, the game completely crashes when battle starts... All was fine for me last night when using .89.

**To Reproduce**
Use Cetra + DX11/DX12

**Comment by wturner859** [comment]
Looks like this can be closed.

**Comment by julianxhokaxhiu** [comment]
Sorry, forgot to mention that is fixed now! Thanks for testing and closing.
