### ISSUE TITLE
[ FF7 ] Lighting is causing battle field to spill into battle menu.

### ISSUE THREAD

**Issue by chrcoluk** [julianxhokaxhiu/FFNx#268]
The lighting feature in recent builds of FFNX is breaking the HP and MP bars in ESUI.

It also breaks vanilla battle UI on the pause box and help box.

**To Reproduce**

In FFNX.toml enable lighting as follows.

enable_lighting = true

**Expected behavior**

No impact on the menu layer.

**Screenshots**

I will attach 2 video's one for ESUI and one for vanilla UI, the mouse pointer shows the problem areas.

ESUI
https://streamable.com/vv6j6d

Vanilla
https://streamable.com/u46kop

**GPU (please complete the following information):**

Nvidia RTX 3080
Driver 465.89

This was reported by multiple users on discord, I am detailing the report and my testing here.

Chris

**Comment by CosmosXIII** [comment]
The PR that fixes this problem is out now:
https://github.com/julianxhokaxhiu/FFNx/pull/269
