### ISSUE TITLE
[ FF7 ] Add support for animated textures

### ISSUE THREAD

**Issue by julianxhokaxhiu** [julianxhokaxhiu/FFNx#27]
The engine by default has support for animated field textures, and that is done by interpolating their color in field scripts, which is then paletted by the driver.

Most notable place where this happens is Aerith House scene, where the light and the waterfall are animated. When those textures are replaced, both of them are fully static.

**Comment by julianxhokaxhiu** [comment]
For anyone stepping in here, this feature is now part of the canary releases. In order to make use of it, it's better to run the game in vanilla with the option `save_textures = yes` enabled.

The number of textures that are created may vary and in order to know if you have dumped them all is to run the scene for at least 2-3 min and check the relative `mod_path` directory output if new files are being created. For example `eals_1` scene ( Aerith House ) generates a total of 172 files. When those are created, it means Nx finished to dump every possible texture iteration.

Then to double-check that you dumped them all, just turn off again the `save_textures` flag and re-run the game. If you see the animations well done! If not, try again and maybe wait a bit longer this time :)

**Comment by daedrixxx2** [comment]
I've tried to do as you said, left the game in the background with nothing in mods/Textures, and waited up to 10 minutes in various fields where there were animations, but in eals_1 for example, I got only 28 png, versus the 172 to be expected. What did I do wrong?
Wouldn't unlpg flevel.lpg be faster and more efficient to find the missing png for animated textures?

**Comment by julianxhokaxhiu** [comment]
> I've tried to do as you said, left the game in the background with nothing in mods/Textures, and waited up to 10 minutes in various fields where there were animations, but in eals_1 for example, I got only 28 png, versus the 172 to be expected. What did I do wrong?

Not sure to be honest, should be working. @satsukiyatoshi for eg. managed to get it working and matched my output as well.

> Wouldn't unlpg flevel.lpg be faster and more efficient to find the missing png for animated textures?
Unfortunately not, you need to emulate the flevel scripting part and compute textures exactly as the engine does. If someone will ever manage to build this layer, then yes, you should be able to do this offline. Anyway, this feature is experimental currently so may change in the future.

Wait for at least one mod pack coming out then you can proceed building your own :)

**Comment by daedrixxx2** [comment]
Having HD animated textures would be a dream, where nothing is lost compared to vanilla low res backgrounds.
Looking forward to it! You're doing great progress guys!

**Comment by satsukiyatoshi** [comment]
@daedrixxx2
might be computer power related + hdd speed limits
to extract all eal textures it take me about 30s with ssd and powerfull cpu (need to extract form ram to png + png compression, will take cpu power)

**Comment by daedrixxx2** [comment]
I have quite a powerful rig: i9 9900k @ 3,6Ghz (still to OC to 5.0Ghz), 32 Gb of ram @3200mhz CL14 and a GTX 970 soon to be replaced by a 3080. But since I considered FF7 to be a "light" game, I installed it on the hdd... maybe that's the problem.

**Comment by julianxhokaxhiu** [comment]
> But since I considered FF7 to be a "light" game, I installed it on the hdd... maybe that's the problem.

One thing everybody doesn't get is that FFNx is targeting `Next-gen` platforms. So the game WAS meant to be lightweight, but not with FFnx which adds a ton of new features and capabilities which do require modern platform capabilities ( SSD for eg. improves loading external textures speed by a huge margin ). So the game itself is lightweight, but if used with what it does provide OOB. FFNx pushes to the extreme your platform to give you the best you can get out of the same game files ( can't say out of the same engine as we do own now video, audio and input ) :)

**Comment by daedrixxx2** [comment]
> One thing everybody doesn't get is that FFNx is targeting Next-gen platforms.

I like this approach! Finally we have the right driver to do justice to FF7/8 and in time we'll get the definitive versions of these games from the "modest" PC versions. Much better than FF7 Remastered on the Windows Store and FF8 Remastered, which still have bugs long patched by the community.
