### ISSUE TITLE
[ FF7 ] VGMStream Ruby Weapon SFX Infinite loop.

### ISSUE THREAD

**Issue by wturner859** [julianxhokaxhiu/FFNx#275]
Ruby Weapon's Whirlsand attack (Sound ID's 261 and 383) loop infinitely. 

Included in link, as always, is a video clip, the traced log(relevant snipped) and a save file.

http://bonez.7thheaven.rocks/8-30-21.7z

**Comment by julianxhokaxhiu** [comment]
Thanks for the report. I'll check and get back as soon as possible.
