### ISSUE TITLE
[ FF7 ] Add support for custom sound effects

### ISSUE THREAD

**Issue by julianxhokaxhiu** [julianxhokaxhiu/FFNx#28]
The driver for now is fully able to replace music in-game but this is not enough.

Until now, in order to replace in-game sound effects, there's a need to fully pack a custom `audio.dat` file with all the tracks inside.

We should implement a layer to load those files from directories, like it happens with Music.

**Comment by myst6re** [comment]
Can you assign me to this issue?

**Comment by julianxhokaxhiu** [comment]
Sure, thank you!

**Comment by julianxhokaxhiu** [comment]
This functionality is now in the code.
