### ISSUE TITLE
[ FF7 + Echo-S ] Crash when loading voice file

### ISSUE THREAD

**Issue by petfriendamy** [julianxhokaxhiu/FFNx#280]
Occasionally, while playing with the Echo-S mod, the game will crash when attempting to load a voice file. This usually seems to happen after playing the game for a while.

Using 7th Heaven v2.3.1.101 with the latest FFNx canary (v1.9.0.198). I've attached the 7th Heaven applog. I also had FFNx generate a crash.dmp, and have included a screenshot from that. If you need the whole file, let me know, I've just left it out for now because the file size is over 1GB.

[applog.txt](https://github.com/julianxhokaxhiu/FFNx/files/7188002/applog.txt)

![crash](https://user-images.githubusercontent.com/65095334/133843093-ded6f2be-d01c-40e6-9870-34ae9068c9c8.png)

**Comment by julianxhokaxhiu** [comment]
I wonder if this is related to #273

What do you think @myst6re ?

**Comment by julianxhokaxhiu** [comment]
@petfriendamy I think you uploaded the wrong log file, because the one in the issue is about 7th. Please upload the `FFNx.log` file.
