### ISSUE TITLE
[ FF7 ] Crash when resizing window

### ISSUE THREAD

**Issue by Tsunamods** [julianxhokaxhiu/FFNx#285]
I get this issue a lot, finally remembered to get the app log for it.
Fairy often when dragging the window to the top of the the screen for Windows to autosize it to full screen it crashes.
[FFNx.log](https://github.com/julianxhokaxhiu/FFNx/files/7367402/FFNx.log)

**Comment by julianxhokaxhiu** [comment]
Thanks for the log. On its on it's very useful but unfortunately it's again an AMD driver issue. Other than suggesting updating to the latest version, I can't do much.

Technically speaking it's a bug related around cache invalidation around D3D12 ( DirectX 12 ).
