### ISSUE TITLE
[ FF7 ] Crash when opening config menu

### ISSUE THREAD

**Issue by Tsunamods** [julianxhokaxhiu/FFNx#286]
Crash when opening config menu, no idea real
[FFNx.log](https://github.com/julianxhokaxhiu/FFNx/files/7367424/FFNx.log)
ly

**Comment by julianxhokaxhiu** [comment]
The crash seems to be unrelated to anything around FFNx, but is instead a GPU driver crash on the DirectX 12 layer. Make sure to use the latest driver releases from AMD ( if you're still on that GPU ).
