### ISSUE TITLE
[ FF7] ERROR: [Device Lost]

### ISSUE THREAD

**Issue by futcharist** [julianxhokaxhiu/FFNx#321]
I've got walls of errors in my log saying:

ERROR: [Device Lost] Blit destination texture (handle 3, '') is not created with `BGFX_TEXTURE_BLIT_DST` flag

I am using the testing version of the music sync feature provided by Myst6re. Does not seem to affect gameplay but is slightly worrying, its not an error I've seen before. The only mods currently active are Ninostyles models in my direct folder

Device name	FewtchZ-Mini
Processor	Intel(R) Xeon(R) CPU E3-1245 v5 @ 3.50GHz   3.50 GHz
Installed RAM	16.0 GB
NVidia Quatro M620

[FFNx.log](https://github.com/julianxhokaxhiu/FFNx/files/7698129/FFNx.log)

**Comment by julianxhokaxhiu** [comment]
Can you please post your `FFNx.toml` config file too? Thanks

**Comment by futcharist** [comment]
Apologies, after some testing I realized it also required lighting to be turned on. If that's an issue to be brought directly to its creator, I will do so.
The only requirement is to enter a field, and evidently also have a model being loaded from the direct folder. There are no other mods active in the attached log.
[Final Fantasy VII.zip](https://github.com/julianxhokaxhiu/FFNx/files/7699098/Final.Fantasy.VII.zip)

**Comment by julianxhokaxhiu** [comment]
Thank you for the report. Patch submitted, feel free to test the next canary :)
