### ISSUE TITLE
[ FF8 Steam ] Chocobo World does not work

### ISSUE THREAD

**Issue by myst6re** [julianxhokaxhiu/FFNx#329]
When trying to start chocobo world menu in the game, there is a message saying "Download error" in FF8 Steam version. I cannot find any log about this for now.

![2021-12-18 19_56_52-New Issue · julianxhokaxhiu_FFNx](https://user-images.githubusercontent.com/8015696/146652802-8c43df82-ebd0-4559-a496-1258f8a04fc7.png)

**Comment by julianxhokaxhiu** [comment]
Interesting, let's keep track of this and enable future investigations. Thanks!

**Comment by myst6re** [comment]
The last trace is about the chocobo music play. When I search it in a decompiler, I find this call right after an occurence of the string "cyocobo.bin". I also searched for the string "Echec téléchargement", ff8-encoded or not, and found nothing.

**Comment by julianxhokaxhiu** [comment]
Was this issue fixed by https://github.com/julianxhokaxhiu/FFNx/pull/330/commits/b69c3ef8948f0c183ba279d2d53e013db6599263 ? Or is it still happening?

**Comment by myst6re** [comment]
This is still happening and unrelated to b69c3ef

**Comment by myst6re** [comment]
Fix in PR #414
