### ISSUE TITLE
[ FF7 ] Texture bug in condor and chocobo mingame (black line)

### ISSUE THREAD

**Issue by satsukiyatoshi** [julianxhokaxhiu/FFNx#34]
In those minigames some textures shows black line (horizontal or vertical).
Show in vanilla game and with custom textures too

One exemple 
![Screen_Shot_029](https://user-images.githubusercontent.com/8547498/82091145-24fefa80-96f7-11ea-80aa-0f59cc9e4080.png)

**Comment by julianxhokaxhiu** [comment]
This is something that is coming out of the default engine. We would need to either fix the data files or intercept vertex calls  ì( which is dangerous and error prone imho ). Any other idea is welcome.

**Comment by julianxhokaxhiu** [comment]
Did various tests on top of the latest code and it seems I'm no more able to replicate this. Did try using various resolutions and various combinations of options ( Internal Scale 4x, AA 16x, etc. ) and there's no trace anymore of black lines.

Can you confirm?
