### ISSUE TITLE
[ FF7 ] Collection of 60FPS bugs/glitches

### ISSUE THREAD

**Issue by tangtang95** [julianxhokaxhiu/FFNx#347]
This is the collection of bugs and glitches related to full 60FPS gameplay feature: 

- **BATTLE mode**
    - [x] Gun 2D effect animation (e.g. Barret or enemy gun's attack) does not always happen
    - [x] Softlock in final battle agains Bizzaro Sephiroth (sometimes when a part dies it does not prompt to change party). The solution is to fix menu FPS with another method 
    - [x] Moves that inflict Mini status has animation glitch
    - [ ] 2D effects are still running at 15 FPS (i.e. magics, enemy skills, enemy moves, etc.)
       - [x] Material effects running at 15 FPS (e.g. Ice1, Ice2, Ice3, ...)
       - [ ] Particle effects are still running at 15 FPS (e.g. Flamethrower, Sewer, Shiva's particles, ...)
       - [ ] Texture pages are still running at 15 FPS (e.g. Fire texture is not changing at 60FPS). This is not fixable via code, but only by changing texture files (Low priority until particle effects are fixed)
    - [x] **Summon's are still running at 15 FPS (Models and camera)**
    - [x] Shiva is blinking at the start
    - [x] "Chocobuckle" enemy skill is running at 15 FPS
    - [ ] Confu magic running at 15 FPS
    - [x] **Few limit break's camera movement are still at running 15 FPS (Need to specify better)**
    - [x] **Few enemy's move camera movement are still at running 15 FPS**
    - [x] Yellow triangle indicator at the top of the current controlled character is animated too fast [_Minor bug_]
    - [x] Enemy attacks animation glitches
        - [x] "Goblin punch" enemy skill has animation glitch
        - [x] "Bomb blast" of Bomb remains with black background after the move
        - [x] Death kill animation when countdown of Death sentence finish
    - [x] Status effect animations are too quick (e.g. sleep zzz animation)
        - [x] Confusion
        - [x] Sleep and silence
    - [x] Ground movement (e.g. formation ID 460 elevator battle in Shinra building) is too quick 
    - [x] Some battle models that interact with each other has animation glitches (this is due to lost frames during interpolation (Need fix in the IRO))
         - [x] Rufus & Chopper, formation ID 464
    - [x] Pointer indicator for target is animating too quickly when selecting action that targets all enemies or all allies

- **FIELD mode**
    - [x] Encounter rate too high
    - [x] Model movements done by decreasing the movement speed introduce bugs/softlocks (e.g. Cloud wrong direction in his past, when confronting Sephiroth, or Biggs stuck when retreating from Reactor 5). Need to obtain a way to achieve the same movement as in 30 FPS but with smoother animation and movement
    - [x] **Some field objects (e.g. rope, propeller, ...) do not animate correctly because the interpolated animation files are not done**
    - [x] Crash after Demon wall boss fight with Cait Sith (bug in wrong offset of opcode)
    - [x] Softlock above train while playing as Cid (map field _zcoal_3_)
    - [x] Dialog message speed is purposely not fixed since it can be regulated (_Minor bug_)
    - [x] [Optional fix in IRO] One train in trainyard moves incorrectly the first time used (which caused some strange animation glitch). Found fix only by editing flevel.lgp (flevel fix compatible with original FPS)
    - [x] Parade in Junon has lots of animation glitches (it seems that the main script of each field model is starting too quickly).
    - [ ] Some animation are sped up due to loops inside script flevel.lgp that use variable counter.
        - [x] [Optional fix in IRO] In blin70_2, Cloud and Barret does not face correctly against Palmer (flevel fixable)
        - [x] [Optional fix in IRO] In woa_2 and woa_3, the background animation cover only half of the screen (flevel fixable)
        - [ ] In some other maps, animated textures might run too quickly due to the loops (e.g. lights, cogs, ...)
    - [x] Great Glacier steps before fainting is halved
    - [x] Turn movement (done by opcode TURNGEN 0xB4 and TURN 0xB5) is not fully supported, 7+1 of them cannot be increased further. They require a new variable that is bigger than a byte. Maybe splitting it into two opcode could be a solution (https://picklejar76.github.io/kujata-webapp/field-op-code-details/b4)
    - [x] Background movement is not smooth (unless a new 2D background engine is implemented, it cannot be fixed)
    - [x] Softlock on one of the last area of the game (map _las0_5_). Fixed in canary version 

- **WORLDMAP mode**
    - [x] Encounter rate too high
    - [x] Dialog message speed
    - [x] Weapon cutscene is glitched 
    - [ ] Midgar Zolom (a.k.a. Snake) is shorter in length due to movement speed reduced (_Minor bug_: need to increase the size of the array containing snake positions)

Do not report these following original unmodded FF7 bug: 
 - Possibility to softlock the player on the edges of first Wutai Bridge. Cannot move the character

**Before reporting new bugs/glitches, make sure you are running the latest canary version of FFNx and also the latest 60 FPS IRO mod (force update on catalog and check if there is a new version). Also double check if the bug or glitch is not already in this list**

**Comment by wonx** [comment]
Hi. I'm not sure it's the right place to post it. I noticed my game crashes when at the start of a battle on the Junon Airport. It crashes even disabling all other mods. I'm using the mod version 1.01 with FFNx-FF7_1998-v1.10.1.105. I attach the logfile.
[FFNx.log](https://github.com/julianxhokaxhiu/FFNx/files/7922257/FFNx.log)

**Comment by julianxhokaxhiu** [comment]
Hi, please consider updating to the latest canary + 60 FPS v1.01 on 7th Heaven, and try again. Thank you.

**Comment by tangtang95** [comment]
> Hi. I'm not sure it's the right place to post it. I noticed my game crashes at the start of a battle on the Junon Airport. It crashes even disabling all other mods. I'm using the mod version 1.01 with FFNx-FF7_1998-v1.10.1.105. I attach the logfile. [FFNx.log](https://github.com/julianxhokaxhiu/FFNx/files/7922257/FFNx.log)

Thanks for reporting. The crash is due to a corrupted interpolated animation file for the Roulette Cannon enemy. The next IRO (probably version 1.02) will contains the correct interpolated animation file.

**Comment by MaxVicioOk** [comment]
the game does not start even with Directx 12, 9, OpenGL, it has graphic problems with Directx 11 and crash with vulkan, which completely hangs the PC, so I cannot record the screen to show the crash with Vulkan

[FFNx (glitch DirectX 12).log](https://github.com/julianxhokaxhiu/FFNx/files/7929570/FFNx.glitch.DirectX.12.log)
[FFNx (Glitch OpenGL).log](https://github.com/julianxhokaxhiu/FFNx/files/7929571/FFNx.Glitch.OpenGL.log)
[FFNx (Glitch Vulkan).log](https://github.com/julianxhokaxhiu/FFNx/files/7929572/FFNx.Glitch.Vulkan.log)
[FFNx (Glitch Directx 11).log](https://github.com/julianxhokaxhiu/FFNx/files/7929573/FFNx.Glitch.Directx.11.log)

https://youtu.be/S4X_OOUQfY0

**Comment by tangtang95** [comment]
> the game does not start even with Directx 12, 9, OpenGL, it has graphic problems with Directx 11 and crash with vulkan, which completely hangs the PC, so I cannot record the screen to show the crash with Vulkan
> 
> [FFNx (glitch DirectX 12).log](https://github.com/julianxhokaxhiu/FFNx/files/7929570/FFNx.glitch.DirectX.12.log) [FFNx (Glitch OpenGL).log](https://github.com/julianxhokaxhiu/FFNx/files/7929571/FFNx.Glitch.OpenGL.log) [FFNx (Glitch Vulkan).log](https://github.com/julianxhokaxhiu/FFNx/files/7929572/FFNx.Glitch.Vulkan.log) [FFNx (Glitch Directx 11).log](https://github.com/julianxhokaxhiu/FFNx/files/7929573/FFNx.Glitch.Directx.11.log)
> 
> https://youtu.be/S4X_OOUQfY0

You are using an outdated version of FFNx (it says 1.9.0.208). If you are using 7th heaven you should download the zip that has this prefix "FFNx-FF7_1998".

Also do not post here if it is unrelated to 60 FPS.

**Comment by MaxVicioOk** [comment]
> > the game does not start even with Directx 12, 9, OpenGL, it has graphic problems with Directx 11 and crash with vulkan, which completely hangs the PC, so I cannot record the screen to show the crash with Vulkan
> > [FFNx (glitch DirectX 12).log](https://github.com/julianxhokaxhiu/FFNx/files/7929570/FFNx.glitch.DirectX.12.log) [FFNx (Glitch OpenGL).log](https://github.com/julianxhokaxhiu/FFNx/files/7929571/FFNx.Glitch.OpenGL.log) [FFNx (Glitch Vulkan).log](https://github.com/julianxhokaxhiu/FFNx/files/7929572/FFNx.Glitch.Vulkan.log) [FFNx (Glitch Directx 11).log](https://github.com/julianxhokaxhiu/FFNx/files/7929573/FFNx.Glitch.Directx.11.log)
> > https://youtu.be/S4X_OOUQfY0
> 
> You are using an outdated version of FFNx (it says 1.9.0.208). If you are using 7th heaven you should download the zip that has this prefix "FFNx-FF7_1998".
> 
> Also do not post here if it is unrelated to 60 FPS.

sorry, I saw several posts in discussions or in "issues" and everyone is told to use the official 7th support channel, but I can't find which one it is, I see that there are several of us who can't find that channel. The last thing I ask for is the link where I am allowed to generate a post about this, because I downloaded the FFNx-FF7_1998, I executed the .reg and the exact same thing keeps happening. I'd appreciate it a lot

**Comment by mjmj83** [comment]
When I turn on the 60FPS mod the game is running in high speed. I think at least 2-3x the normal speed (I guess x4 the speed: 60 fps = 4 x 15 fps). It happens on my Macbook Pro Max (2021) with Windows 11 on Parallels, so I tried it on my Windows 10 machine (i7-10750H, 32GB, RTX 2070 super). Tried switching between Vulkan, DirectX etc, but.. no change.

Running 7th Heaven v2.3.3.0.

I feel kinda stupid it happens to me, since it happens on both my systems, so it could very well be me. I couldn't find any post on youtube or here mentioning the same issue.

**Comment by tangtang95** [comment]
Have you downloaded the correct version of FFNx? It has to be the FFNx-**FF7_1998** version 1.10.1.120+
You can check your version by enabling show Driver Version in 7th Heaven -> Game Driver -> Advanced. Then run the game and check on the top left the FFNx driver version

**Comment by mjmj83** [comment]
Yes, that was it! Somehow I previously installed 1.10.1.0. Now with 1.10.1.121 it's running as intended.

This is awesome. Thank you guys soooo much!

**Comment by MaxVicioOk** [comment]
Hello. It just happened to me that, in the temple of the elders, after fighting against the wall, Cait Sith enters, speaks a bit and the game crashes. I started to test what mod it could be and I realized that it is for the 60FPS one. I understand that it is a pre-release, I just wanted to let you know in case you hadn't found that glitch. 

Another thing that is in sight, but just in case I mention it, is that with the 60fps mod, cloud has his arms further apart than without the mod

[FFNx (Glitch cait sith templo ancianos 60FPS).log](https://github.com/julianxhokaxhiu/FFNx/files/7963188/FFNx.Glitch.cait.sith.templo.ancianos.60FPS.log)

![crash templo de los ancianos 2](https://user-images.githubusercontent.com/98363423/151652214-04f1458a-0115-41bc-ba21-c7e99e9cb0bf.png)

![cloud sin 60fps](https://user-images.githubusercontent.com/98363423/151652222-b6d0d92e-2b57-4c81-a306-5467cf9adb1d.png)

![cloud a 60fps](https://user-images.githubusercontent.com/98363423/151652228-522d851f-2aa3-4e26-add7-3032fced0031.png)

**Comment by tangtang95** [comment]
@MaxVicioOk Thanks for reporting the crash. I forgot to add it on the list, but I already knew about it. 

For the model that has a different arm position is because the mod isn't fully compatible with 60 FPS mod. The mod needs to add their own interpolated animations for 60 FPS

**Comment by YozoraLeonstrife** [comment]
Crash in every battle of airport zone of Junon area.
I tried without 60 fps mod and work.

![image](https://user-images.githubusercontent.com/98664755/151674931-b05d9471-4e59-4f7b-bc5f-96b68d5dca08.png)

**Comment by tangtang95** [comment]
@YozoraLeonstrife That's probably the crash related to the corrupted animation file of the enemy Roulette Cannon (it will be fixed in next 60 FPS IRO)

**Comment by Neffina** [comment]
hi for me the 2D effect animation of weapons (e.g. barret or enemy weapon attack) is not always working properly the 2D effect animation still not working ?

**Comment by tangtang95** [comment]
@Neffina Oh sorry, it's just for my testing build that works because I still haven't published that fix. I'm not keeping a private list, so this reflects more my situation than the public situation. Maybe I should point it out. Let me fix it

**Comment by Neffina** [comment]
Then I still have the problem after the fight with APS that Aerith wants to run to Cloud to rejoin the group but gets stuck and doesn't go any further

**Comment by tangtang95** [comment]
@Neffina Are you running a higher version of 1.10.1.120 of FFNx? If you are in discord qhimm, better to start a conversation there

**Comment by Neffina** [comment]
have the current one on it FFNx-v1.10.1.128

**Comment by wonx** [comment]
Hi. I noticed an animation speed issue with the 60fps mod. When escaping from the Shinra building, the elevator movement (up and down) during the fight against the two bosses (Hundred Gunner and Heli Gunner) is too fast.

**Comment by wonx** [comment]
Same with the Midgar Expressway chase. Everything goes twice as fast as it should and the motorbike is too hard to control.

**Comment by TheRockstar14** [comment]
how can i download the latest version or update my FFNx because all I can find is the 1.10.1.0 and i dont want to risk the canary version

**Comment by tangtang95** [comment]
@wonx I know about the elevator and I did already wrote that on the list of bugs. While for bike chase, the latest canary FFNx runs the bike chase at 30 fps. So the game is still playable.

@TheRockstar14 if you want to test 60 fps you can only do it by downloading the canary version , as said it's in beta so use it at your own risk

**Comment by Neffina** [comment]
In the Shinra building on the 66th floor, the movements have a slowdown?

**Comment by Neffina** [comment]
when you walk past the elevator

**Comment by tangtang95** [comment]
@Neffina If it's a lag spike in which your FPS drops down then it's usually either because you activated lighting and you are still using the unoptimized version or you have animated textures on.

**Comment by Neffina** [comment]
animated textures off Gesendet von Yahoo Mail für iPhone


Am Montag, Januar 31, 2022, 4:45 PM schrieb Tang-Tang Zhou ***@***.***>:




@Neffina If it's a lag spike in which your FPS drops down then it's usually either because you activated lighting and you are still using the unoptimized version or you have animated textures on.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wonx** [comment]
@Neffina , I have noticed slowdowns in some floors the Shinra building, but in my ae they were caused by animated textures, not by lightning. So that's another thing  to check.

**Comment by Neffina** [comment]
what is now different in all the videos e.g. Junion airport if you press the switch and shut down you are awake if you move more slowly now what yes to the original yes fixed

**Comment by DNewton45** [comment]
I seem to be having fairly consistent unhandled exception issues with the FFNx driver, but am uncertain whether it is the 60FPS mod, FFNx, or something else. It's worth mentioning that, prior to using both FFNx and the 60FPS mod, I did not have these issues, so I am fairly confident one or both of these mods are the cause.

The current build I am using is: FFNx driver version 1.10.1.170 (I will likely grab the latest version later today)

My most recent crash happened during the scene that takes place very shortly after Rufus' "death" in Disc 2. I seem to recall that the scene faded to black in preparation to change scene locations from the inside of the Shinra meeting room, back to the party on the Highwind, when the unhandled exception occurred.

I should mention that these exceptions seem to get thrown either when a scene transition occurs (usually after it fades to black and attempt to load the next area) or when it attempts to load an FMV (one example being a crash that happened when I tried to use the lift in Junon that goes up to the upper area. These crashes are not consistent and often occur after about an hour of play and I can usually boot the game back up and continue without the crash happening again.

While reviewing the crash log, I noticed this line: [00329246] TRACE: *** Exception 0xc0000005, address 0xf3641d7 ***

Below this line, near the bottom of the trace stack, it says this: [00329246] TRACE: 0F3641D7 (FFNx): (filename not available): common_load_texture

Below this it repeatedly says: [00329246] TRACE: 006711F0 (FF7): (filename not available): (function-name not available)

Sandwiched between these lines are these two lines, after which, it repeats the above lines a few more times before the stack ends:

[00329246] TRACE: 0F3B287E (FFNx): (filename not available): field_load_textures_helper
[00329246] TRACE: 0F3B26EA (FFNx): (filename not available): field_load_textures

**Comment by duke912** [comment]
> @julianxhokaxhiu
> 
> No problem, I've attached it here.
> 
> [FFNx.log](https://github.com/julianxhokaxhiu/FFNx/files/8062690/FFNx.log)

I started getting random crashes at version 154 (if I remember correctly) and over, fairly easy to replicate for me, just load a save and go to Kalm and enter the houses, pub, etc. The game will crash within a minute or so and, if I enable lightning in ffnx.toml, it's even more unstable and most of the time will crash as I enter Kalm. So I ended up using version 150 and lightning disabled seems to be the most stable way to play with 60fps (as of now at least).

**Comment by julianxhokaxhiu** [comment]
> 

The issue seems to be unrelated to FFNx and is most probably related to 7th as you're using to load your mods. Please approach the support channels on Discord.



> > @julianxhokaxhiu
> > No problem, I've attached it here.
> > [FFNx.log](https://github.com/julianxhokaxhiu/FFNx/files/8062690/FFNx.log)
> 
> I started getting random crashes at version 154 (if I remember correctly) and over, fairly easy to replicate for me, just load a save and go to Kalm and enter the houses, pub, etc. The game will crash within a minute or so and, if I enable lightning in ffnx.toml, it's even more unstable and most of the time will crash as I enter Kalm. So I ended up using version 150 and lightning disabled seems to be the most stable way to play with 60fps (as of now at least).
> 
> Edit: Only play in DX11, as it is the most stable renderer to use.

@duke912 Please refrain from such suggestions here. This ticket is about testing 60FPS issues and bugs and in order to provide feedback you MUST be always on the latest FFNx canary version. Anything else is considered off-topic.

**Comment by DNewton45** [comment]
@julianxhokaxhiu Ah, ok. Apologies for the mistake.

**Comment by Aynath** [comment]
Hi there, I've been playing with the latest ffNX (252) and 7th Heaven manager 2.3.3.20, the latest up to date. I have a problem regarding the 60 FPS mod, in battles, Cid's attacks' sounds are the same as Cloud's. For some reason if I disable the mod, Cid will have his sounds back. If I enable the mod again, Cid will inherit Cloud's sounds again. I don't know how it is related; I've tried a complete reinstallation but it stills occurs, even with previous FFNX and 7th Heaven versions. I'm surely missing something because it doesn't seem a known bug at all.

**Comment by julianxhokaxhiu** [comment]
@tangtang95 can you please check the issue #429 ? Thank you in advance

**Comment by tangtang95** [comment]
> @tangtang95 can you please check the issue #429 ? Thank you in advance

Seems that its FFNx version is not up to date. He put `FFNx: 1.10.1.197+`

**Comment by MaxVicioOk** [comment]
Hello, people. I tell you about this bug that I found.
In the northern crater, before Cloud delivers the Black Matter to Sephiroth, you have to go through some air currents, which if the 60FPS mod is activated, the animation of the wind and lightning are accelerated, which makes it difficult to pass . I would pass a video showing it, but it is too heavy for this page. If you need I can pass it on one of the discord channels
Sorry for how I write, I'm using the google translator.

**Comment by MaxVicioOk** [comment]
Hello, people. I tell you about this bug that I found.
In the northern crater, before Cloud delivers the Black Matter to Sephiroth, you have to go through some air currents, which if the 60FPS mod is activated, the animation of the wind and lightning are accelerated, which makes it difficult to pass . I would pass a video showing it, but it is too heavy for this page. If you need I can pass it on one of the discord channels
Sorry for how I write, I'm using the google translator.

![image](https://user-images.githubusercontent.com/98363423/162589074-1fb87c7b-2492-441a-9862-0a146ea29018.png)
![image](https://user-images.githubusercontent.com/98363423/162589079-297c8817-820e-48cf-bcd1-ef69d55c8214.png)

**Comment by tangtang95** [comment]
@MaxVicioOk this issue cannot be solved unless the flevel maps (script of field maps) are retouched. This is already done in 60 fps mod but it has to be activated by double click the mod to go into options and then enable "flevel map fix". However this conflicts with other mods that modify the same map (probably your spanish retranslation mod touches that map)

**Comment by tangtang95** [comment]
@ArhumMK Hybrid 60fps is not being worked on, this is only for complete 60 fps

**Comment by tangtang95** [comment]
No, there are no plans for that. It's already too complex as it is

**Comment by SquarelyCircle** [comment]
I'm getting a graphical glitch that goes away when I turn off the 60FPS Gameplay mod in 7th Heaven.
![20220623194718_1](https://user-images.githubusercontent.com/5598399/175448420-0ec13d5e-1ed2-4678-a29f-c5f0b69ff5b0.jpg)

The backgrounds are drawn with lines/squares on them, which blink in and out of existence. By changing various options, I can slightly modify how the background boxes come and go. By setting to "stretched" instead of 4:3 ratio, I can get them to disappear when I'm not moving, but everything looks really weird when it's stretched, and the lines flash in and out of existence when I walk around.

My monitor is 1440p, which I thought might be related to this.
CPU: AMD Ryzen 5950X
GPU: GeForce RTX 3080 (can't remember which brand)
OS: Windows 11
Running on DX11
Running a variety of other mods that change the graphics.

**Comment by SquarelyCircle** [comment]
Turning off anisotropic filtering and antialiasing seems to have fixed the issue. Still a strange interaction that only occurs with this mod on.

**Comment by tangtang95** [comment]
@SquarelyCircle Those lines are a consequence of the implementation of smooth scrolling background. By going from integer values to float values, it introduced bad pixels from the texture when using antialiasing. I don't know if it's possible to fix, but right now the best is to play with no antialiasing and an internal resolution scale that is a power of 2.

**Comment by SquarelyCircle** [comment]
Thank you for replying. It's refreshing to get a quick reply on an issue like this. I'll follow your instructions.

**Comment by LaZar00** [comment]
I'm not sure if Reno attack "Pyramid", the purple light is among the battle features of 60FPS, but I think that it should be improved if possible, should it be?
https://user-images.githubusercontent.com/46090031/178126108-102f0042-7ccf-4ea9-a970-b72c14cb034d.mp4

**Comment by tangtang95** [comment]
@LaZar00 The remaining battle effects require too much work, there are some that has too many particles and cannot be easily interpolated. I don't know if this purple light is one of them, but from the video, it seems fine to me

**Comment by LaZar00** [comment]
I understand that 60FPS is not an easy thing and a lot of RE needs to be done to achieve that.

But in this case, the purple circle seems not enough smooth when talking about 60FPS. Of course it is shown correctly, there are not problems at all, I only was suggesting an improvement if possible.

**Comment by Alexiels** [comment]
Hello! I have an issue, when i use the 60/30 FPS on battle (set on 30) the enemies and cloud are like 2x or 3x speed while Barret is normal speed, dont know how can really fix it, i saw some youtube videos and everything runs ok (enemies, characters, etc)

**Comment by Alexiels** [comment]
> @Alexiels Make sure to have FFNx updated (latest stable version is 1.15.0). You also need to have mods orderered correctly. There is a 1/9 button on the right side bar of 7th heaven that automatically orders the mods.
> 
> For further help, go to the discord you can find on the README

Thanks, I already ordered the mods with the 1/9 button, the FFNx is 1.15, start a new game and then when the first fight starts it crash, it didn't crashed before because I was using a save (I installed the mod after ) I don't know what to do, my pc build:

Asus Rog strix, 3070 rtx, 32 GB ram, 2k 165hz screen, AMD Ryzen 9

![IMG20230502171004](https://user-images.githubusercontent.com/17600994/235723318-09a734e8-24d1-40bc-97d6-4143f35f44a9.jpg)

**Comment by tangtang95** [comment]
> > @Alexiels Make sure to have FFNx updated (latest stable version is 1.15.0). You also need to have mods orderered correctly. There is a 1/9 button on the right side bar of 7th heaven that automatically orders the mods.
> > For further help, go to the discord you can find on the README
> 
> Thanks, I already ordered the mods with the 1/9 button, the FFNx is 1.15, start a new game and then when the first fight starts it crash, it didn't crashed before because I was using a save (I installed the mod after ) I don't know what to do, my pc build:
> 
> Asus Rog strix, 3070 rtx, 32 GB ram, 2k 165hz screen, AMD Ryzen 9
> 
> ![IMG20230502171004](https://user-images.githubusercontent.com/17600994/235723318-09a734e8-24d1-40bc-97d6-4143f35f44a9.jpg)

I'm not sure what is happening. I don't think it's an issue with 60 FPS. If you enable only 60 FPS, does it crash? I still recommend going to Discord for 7th heaven support

**Comment by tangtang95** [comment]
The softlock related to #569 has been fixed with the latest canary v1.15.0.116

**Comment by catalyst-ffxi** [comment]
Hi,

I've noticed that safe code in the Nibelheim mansion is particularly difficult to enter correctly under 60 fps. I didn't see that listed here yet so thought I'd mention it, sorry if I missed it.

Thanks for the amazing mod!

**Comment by DenisNovac** [comment]
Hello! I found three bugs during my playthrough:

Whirlwind Maze - wind wall (the one with green line: [youtube link](https://youtu.be/uHRUkQzgJRs?si=u2YdtyloafU_v0D7&t=305)) animation glitching (impossible to time it correctly, just passed randomly);

Fort Condor segment crashed the game when i put too many units (i believe it crashed on tristones);

Sephiroth' Super Nova animation doesn't work - only show black sky.

**Comment by gtao725** [comment]
Hi! Not sure if its just me, but Knights of the Round summon crashes the game every time it is triggered with 60fps mod turned on. At 30fps it is fine. I have tried disabling all other mods leaving just 60fps mod on and still it crashes. Just wondering if anyone else has the same issue?

**Comment by SonicRay100** [comment]
I've discovered a bug that occurs when using "NinostyleHD animations" in the "Advanced Field Animations (60 FPS)" section of the 60 FPS mod. It doesn't occur when using "Original" or "ChaOS animations". I've tested this with just the 60 FPS mod active so I know no other mod is causing this.

What Happens is some NPCs will not play their animation immediately when interacted with. There's a 4 or so second delay. At first I thought the game froze and then they suddenly played their animation and started talking. It doesn't break the game thankfully. I should point out that spamming an interaction might get them to react immediately but it's not consistent.

I don't have a list but I can point to one NPC that this happens with. He's in North Corel. Here's his details when opening flevel.lgp in Makou Reactor:

File: ncorel
Id: 450

Id: 22
Group: man3

Thanks for reading :).

**Comment by satsukiyatoshi** [comment]
> I've discovered a bug that occurs when using "NinostyleHD animations" in the "Advanced Field Animations (60 FPS)" section of the 60 FPS mod. It doesn't occur when using "Original" or "ChaOS animations". I've tested this with just the 60 FPS mod active so I know no other mod is causing this.
> 
> What Happens is some NPCs will not play their animation immediately when interacted with. There's a 4 or so second delay. At first I thought the game froze and then they suddenly played their animation and started talking. It doesn't break the game thankfully and everything proceeds as normal once the NPCs animation plays. I should point out that spamming an interaction might get them to react immediately but it's not consistent.
> 
> I don't have a list but I can point to one NPC that this happens with. He's in North Corel. Here's his details when opening flevel.lgp in Makou Reactor:
> 
> File: ncorel Id: 450
> 
> Id: 22 Group: man3
> 
> Thanks for reading :).

it's not related to 60 fps as the same bug also occurs in OG fps

**Comment by SonicRay100** [comment]
> it's not related to 60 fps as the same bug also occurs in OG fps

Really? I can't seem to replicate that at all without "NinostyleHD animations" activated. Is it documented anywhere? I was looking around to see if it was a known bug but I found nothing. Regardless, is there a fix for it?

**Comment by satsukiyatoshi** [comment]
> > it's not related to 60 fps as the same bug also occurs in OG fps
> 
> Really? I can't seem to replicate that at all without "NinostyleHD animations" activated. Is it documented anywhere? I was looking around to see if it was a known bug but I found nothing. Regardless, is there a fix for it?

this bug have been reported to me some days ago only, so i just started investigating on it.
it's not related to 60 fps, try with 30fps (AKA OG fps) and a 3d models pack, you'll get the same bug.
it's related to the breathing animation used by chaos and nino 3d model in my AIO pack (just found the culprist some minuts ago)

i'll correct this bug asap, if i can't fix the breating's bug (it may be realy complex because breathing animation is 4 seconds lenght and originaly there's no such a animation so i suspect the game's script to not stop animation before some dialog - logic if there's no animation in those script in OG), i'll remove the breathing

**Comment by SonicRay100** [comment]
Ah it makes sense now. To be honest I forgot the characters didn't have breathing animations in the first place. It's not really too much of an issue though, since it's not game breaking and it does give a bit more life to the characters. Perhaps an option to disable the breathing for those who can't deal with it if possible would be better if a solution can't be found?

**Comment by tangtang95** [comment]
Hi everyone, I will close this issue as there is no need to collect all bugs and glitches related to 60 fps. There is nothing more planned to fix. All limitations are listed in the mod's README (https://github.com/tangtang95/ff7-60fps-mod/blob/main/src/Readme.txt) and here. If new bugs are found out, please open a new issue.

Thanks everyone for the help in testing and debugging!
