### ISSUE TITLE
hext code toggle option in toml

### ISSUE THREAD

**Issue by chrcoluk** [julianxhokaxhiu/FFNx#350]
Is it possible to add a on/off switch in the toml for processing the hext folder defaulting to on, this could then allow me in ESUI to add a 7th heaven <FFNxConfig> override in my mod.xml to disable the included UI hext code.

**Comment by julianxhokaxhiu** [comment]
I don't see a valid point in adding such a flag when you can simply delete the hext files in the relative path and they won't be loaded. If there's a conflict in the distributed version by 7th, it has to be fixed there.
