### ISSUE TITLE
[ FF7 ] Wildly wrong DEF and MDEF values from armor

### ISSUE THREAD

**Issue by ogelsan** [julianxhokaxhiu/FFNx#353]
FFNx seems to be producing the wrong values for DEF and MDEF on armor. This only applies to the final character calculation; the correct value is displayed in menus for the items themselves. The bronze bangle still works as expected, but every other piece of armor that I tested is bugged. When the MDEF fix is disabled in FFNx.toml, it's calculated as expected of the vanilla bug--MDEF = Spirit for all armor--but DEF is still erratic.

It only seems to occur with the current canary build (1.10.1.105).

**To Reproduce**
Equip any armor other than a bronze bangle on any character, and then view the status screen. The final DEF and MDEF values will be different than expected.

**Additional Context**
I tried a number of different configurations to suss out FFNx as the source, including without mods, without 7th Heaven, and a fresh installation using Aali's driver.

And after spending more time than I probably should've poking around in memory and assembly, I've worked out that the problem seems to be coming from a 4-byte misalignment in the `armor_data` struct. Comparing the bugged values of the first 15 armor pieces to the data in memory, I found that they line up perfectly if you were to treat each struct as 4 bytes longer than it actually is.

Values recorded in game:
```
Bronze Bangle:      8/   0 (correct)
Iron Bangle:     >184/>147
Titan Bangle:       5/   0
Mythril Armlet:     0/   0
Carbon Bangle:   >184/   1
Silver Armlet:      0/>147
Gold Armlet:     >184/>147
Diamond Bangle:  >184/>147
Crystal Bangle:  >184/>147
Platinum Bangle:   43/  24
Rune Armlet:     >184/>147
Edincoat:           7/   6
Wizard Bracelet:    0/   0
Adaman Bangle:   >184/   1
Gigas Armlet:       0/>147
```
First 15 armor structs aligned to 36 bytes:
```
00FF 0800 0000 FFFF 0000 0000 0000 0000 0000 FF01 0000 00FF 00FF FFFF 00FF FFFF FEFF FFFF 
00FF 0A02 0000 FFFF 0005 0000 0000 0000 0001 FF01 0000 00FF 00FF FFFF 00FF FFFF FEFF FFFF 
00FF 0E04 0200 FFFF 0005 0500 0000 0000 0001 FF01 0000 00FF 00FF FFFF 00FF FFFF FEFF FFFF 
00FF 1208 0300 FFFF 0006 0700 0000 0000 0001 FF01 0000 00FF 00FF FFFF 00FF FFFF FEFF FFFF 
00FF 1B0E 0300 FFFF 0006 0705 0000 0000 0001 FF01 0000 00FF 00FF FFFF 00FF FFFF FEFF FFFF 
00FF 2216 0400 FFFF 0006 0705 0500 0000 0001 FF01 0000 00FF 00FF FFFF 00FF FFFF FEFF FFFF 
00FF 2E1C 0400 FFFF 0006 0706 0700 0000 0001 FF01 0000 00FF 00FF FFFF 00FF FFFF FEFF FFFF 
00FF 3925 0600 FFFF 0006 0706 0705 0000 0001 FF01 0000 00FF 00FF FFFF 00FF FFFF FEFF FFFF 
00FF 462D 0801 FFFF 0006 0706 0706 0700 0001 FF01 0000 00FF 00FF FFFF 00FF FFFF FEFF FFFF 
00FF 140C 0000 FFFF 0005 0500 0000 0000 0002 FF01 0000 00FF 00FF FFFF 00FF FFFF FEFF FFFF 
00FF 2B18 0500 FFFF 0005 0505 0500 0000 0002 FF01 0000 00FF 00FF FFFF 00FF FFFF FEFF FFFF 
00FF 3221 0000 FFFF 0005 0505 0505 0505 0001 FF01 0000 00FF 02FF FFFF 05FF FFFF FEFF FFFF 
FFFF 0655 0303 FFFF 0006 0706 0706 0706 0701 FF01 0000 00FF 02FF FFFF 14FF FFFF FEFF FFFF 
00FF 5D17 0000 FFFF 0006 0700 0000 0000 0001 FF01 0000 00FF 00FF FFFF 00FF FFFF FEFF FFFF 
00FF 3B00 0000 FFFF 0002 0302 0301 0000 0000 FF01 0000 00FF 00FF FFFF 1EFF FFFF FEFF FFFF 
```
First 15 armor structs aligned to 40 bytes:
```
00FF 0800 0000 FFFF 0000 0000 0000 0000 0000 FF01 0000 00FF 00FF FFFF 00FF FFFF FEFF FFFF 00FF 0A02 
0000 FFFF 0005 0000 0000 0000 0001 FF01 0000 00FF 00FF FFFF 00FF FFFF FEFF FFFF 00FF 0E04 0200 FFFF 
0005 0500 0000 0000 0001 FF01 0000 00FF 00FF FFFF 00FF FFFF FEFF FFFF 00FF 1208 0300 FFFF 0006 0700 
0000 0000 0001 FF01 0000 00FF 00FF FFFF 00FF FFFF FEFF FFFF 00FF 1B0E 0300 FFFF 0006 0705 0000 0000 
0001 FF01 0000 00FF 00FF FFFF 00FF FFFF FEFF FFFF 00FF 2216 0400 FFFF 0006 0705 0500 0000 0001 FF01 
0000 00FF 00FF FFFF 00FF FFFF FEFF FFFF 00FF 2E1C 0400 FFFF 0006 0706 0700 0000 0001 FF01 0000 00FF 
00FF FFFF 00FF FFFF FEFF FFFF 00FF 3925 0600 FFFF 0006 0706 0705 0000 0001 FF01 0000 00FF 00FF FFFF 
00FF FFFF FEFF FFFF 00FF 462D 0801 FFFF 0006 0706 0706 0700 0001 FF01 0000 00FF 00FF FFFF 00FF FFFF 
FEFF FFFF 00FF 140C 0000 FFFF 0005 0500 0000 0000 0002 FF01 0000 00FF 00FF FFFF 00FF FFFF FEFF FFFF 
00FF 2B18 0500 FFFF 0005 0505 0500 0000 0002 FF01 0000 00FF 00FF FFFF 00FF FFFF FEFF FFFF 00FF 3221 
0000 FFFF 0005 0505 0505 0505 0001 FF01 0000 00FF 02FF FFFF 05FF FFFF FEFF FFFF FFFF 0655 0303 FFFF 
0006 0706 0706 0706 0701 FF01 0000 00FF 02FF FFFF 14FF FFFF FEFF FFFF 00FF 5D17 0000 FFFF 0006 0700 
0000 0000 0001 FF01 0000 00FF 00FF FFFF 00FF FFFF FEFF FFFF 00FF 3B00 0000 FFFF 0002 0302 0301 0000 
0000 FF01 0000 00FF 00FF FFFF 1EFF FFFF FEFF FFFF 00FF 524A 0000 FFFF 0006 0706 0706 0700 0001 FF01 
0000 00FF 00FF FFFF 00FF FFFF FEFF FFFF 00FF 3756 0F32 FFFF 0006 0706 0700 0000 0001 FF01 0000 00FF 
```
Glancing at the code, though, nothing seems to have changed with `armor_data`, so I don't have a clue where the extra 4 bytes would be coming from.

**Comment by julianxhokaxhiu** [comment]
Thanks for reporting. The 4-bytes issue on the struct looks like a misalignment of the structure in memory. I'll try to check what happened compared to past releases and let you know my findings ( or a possible fix ).

**Comment by julianxhokaxhiu** [comment]
Ok issue found, please wait for the next canary to come out and feel free to try. Thank you :)

**Comment by ogelsan** [comment]
Nice! Glad to hear it wasn't much trouble to sort out.

**Comment by ogelsan** [comment]
Wasn't expecting the new canary out that fast. Just tested it really quick and it looks fixed. Thanks!

**Comment by julianxhokaxhiu** [comment]
Enjoy :)
