### ISSUE TITLE
Game crash with any render backend / OpenGL, Directx 11, Directx 12 and Vulkan

### ISSUE THREAD

**Issue by MaxVicioOk** [julianxhokaxhiu/FFNx#362]
Hi, the game does not start even with Directx 12, 9, OpenGL, it has graphic problems with Directx 11 and crash with vulkan, which completely hangs the PC, so I cannot record the screen to show the crash with Vulkan.

sorry for my english, i'm using google translate

[FFNx (Glitch Directx 12).log](https://github.com/julianxhokaxhiu/FFNx/files/7932625/FFNx.Glitch.Directx.12.log)
[FFNx (Glitch OpenGL).log](https://github.com/julianxhokaxhiu/FFNx/files/7932628/FFNx.Glitch.OpenGL.log)
[FFNx (Glitch Directx 11).log](https://github.com/julianxhokaxhiu/FFNx/files/7932629/FFNx.Glitch.Directx.11.log)
[FFNx (Glitch Vulkan).log](https://github.com/julianxhokaxhiu/FFNx/files/7932630/FFNx.Glitch.Vulkan.log)

Video: https://youtu.be/S4X_OOUQfY0 

 Operating System: Windows 10 Pro 64-bit (10.0, Build 19043) (19041.vb_release.191206-1406)
                 Language: Spanish (Regional Setting: Spanish)
      System Manufacturer: Gigabyte Technology Co., Ltd.
             System Model: B365M DS3H
                     BIOS: F5 (type: UEFI)
                Processor: Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (6 CPUs), ~2.9GHz
                   Memory: 16384MB RAM
      Available OS Memory: 16326MB RAM
                Page File: 9116MB used, 15401MB available
              Windows Dir: C:\Windows
          DirectX Version: DirectX 12
        Graphic: RX 570 8Gb

**Comment by julianxhokaxhiu** [comment]
As you're using 7th Heaven, please ask for support on the relative support channels. Cheers!
