### ISSUE TITLE
[ FF7 ] Add a soft reset (with start + select for example)

### ISSUE THREAD

**Issue by satsukiyatoshi** [julianxhokaxhiu/FFNx#37]
In the psx version a soft reset is possible with start+select+l1+l2+r1+r2
This is a great feature so a new save can be loaded instead of quit then launch the game again.

Even better would be to be able the show the load / new game option from start + select for exemple (not the full key combination like in psx or it'll be hard to do in keyboard because of keys multiplexing in most keyboards)

**Comment by julianxhokaxhiu** [comment]
Starting with the new canary Soft Reset will now be a thing, it will work EVERYWHERE and it will be instant, just like on PSX :)

Shortcuts are:
- Using the Keyboard: CTRL+R
- Using the Gamepad (XInput only): L1+L2+R1+R2+START+SELECT

Enjoy!
