### ISSUE TITLE
[ FF7 ] Right trigger does not work when "Analogue Controls" are enabled

### ISSUE THREAD

**Issue by duke912** [julianxhokaxhiu/FFNx#376]
When you set enable_analogue_controls = true in ffnx.toml, the right trigger will not work in-game, I set it to pagedown in 7th heaven settings, but even trying to setting in game (through customize option), it won't work. All the other buttons works, including left trigger, already tried change deadzone, etc. but still doesn't work.

Tested with xbox series controller, and using the latest release [1.10.1.150]

**Comment by julianxhokaxhiu** [comment]
It's not really a bug on a per se, but more a side effect of that flag. Let's see what the original author, @CosmosXIII, has to say about it.

**Comment by duke912** [comment]
> It's not really a bug on a per se, but more a side effect of that flag. Let's see what the original author, @CosmosXIII, has to say about it.

I thought about that at first, but LT still works outside of battles (I set to pageup, but I can set to anything else), whereas RT only work to zoom in camera in battle. The only workaround I found is to use something like antimicro and set RT to pgdown, and it'll now work the same way as LT (control camera in battles and work on menus, etc as well).

**Comment by CosmosXIII** [comment]
When analog controls are enabled R2 is remapped to R3 to free the analog trigger for zoom controls. So if you want to use that button just click the right analog stick (R3 button). This is not so big of a problem for what the game uses this button, which is as far as I know just to show the "targets" GUI in battles and change the camera mode in worldmap mode.
That said, this seems to be a problem when using the speed hack shortcuts so I will look into that when as soon as I find a little free time.

**Comment by faospark** [comment]
> When analog controls are enabled R2 is remapped to R3 to free the analog trigger for zoom controls. 

it conflicts / breaks the Gamepad Shortcuts for the ff : Speedhack, Auto-Attack and Soft Reset
https://github.com/julianxhokaxhiu/FFNx/blob/master/docs/shortcuts.md

Since R2 is remapped to R3 the gamepad/controller shortcut for speedhack becomes L2+R3 + Up o Down 
while it can work .... L2+R3 is the shortcut for Auto-attack 
another things is it is not easy try to press R3 on the soft reset combination.
