### ISSUE TITLE
[ Music ] Shuffle is not completely random

### ISSUE THREAD

**Issue by myst6re** [julianxhokaxhiu/FFNx#392]
Carlucci reported that music shuffle plays musics always in the same order, once the game is started.

I suspected something with the seed generator, but it seems that it is regenerated at every call:

```cpp
inline int getRandomInt(int min, int max)
{
    std::mt19937 rng(rand());
    std::uniform_int_distribution<int> gen(min, max);

    return gen(rng);
}
```

I propose to change the first line to:

```cpp
std::mt19937 rng(std::chrono::system_clock::now().time_since_epoch().count());
```

**Comment by julianxhokaxhiu** [comment]
Fine by me, I wonder though because i think that's used everywhere ( SFX for eg. ) and it works as expected. Maybe he's using the wrong keyword in his `config.toml`? Are you able to reproduce the issue?
