### ISSUE TITLE
[ FF7 ] Add Ficedula Ultrasound native implementation logic

### ISSUE THREAD

**Issue by julianxhokaxhiu** [julianxhokaxhiu/FFNx#42]
At the moment in order to add voice acting into the game, there's a need for an external tool done by Ficedula named [Ultrasound](http://forums.qhimm.com/index.php?topic=15342.0).

The goal of this issue is to add native implementation of this layer within FFNx.

**Comment by Extapathy** [comment]
I've added hooks for the message logic and got the field id and dialog id, so it should be possible to load some external files once the rest of the sound work is complete.

**Comment by julianxhokaxhiu** [comment]
Blocked by #28 ( which will introduce the possibility to play a sound file given a path )

**Comment by julianxhokaxhiu** [comment]
This feature has been implemented and we now have full support for Voice acting on game text messages.
