### ISSUE TITLE
[ FF8 ] Add support for Horizon concert instrument replacement

### ISSUE THREAD

**Issue by myst6re** [julianxhokaxhiu/FFNx#43]
Happens at Horizon during the concert: instruments are selected by script, via the choice_music opcode.

We can hook to a subfunction of opcode_choice_music, but this means rewrite this opcode almost completely. Or hook to the four subs that interact with DirectMusic segments directly (but for this solution we need to find a way to know the filename of each instruments).

This opcode should be the last one using DirectMusic, everything else (SFX and music) use DirectSound with the external_music plugin enabled.

**Comment by julianxhokaxhiu** [comment]
I renamed the issue as we do have now a full blow multi-track audio engine support. All is left to do now is hook the responsible subs and add playback via the new audio engine.
