### ISSUE TITLE
[ FF7 ] External FMV audio too low

### ISSUE THREAD

**Issue by wturner859** [julianxhokaxhiu/FFNx#441]
External FMV audio plays much too low. The exact same tracks that used to be embedded into the video files can barely be heard now that they've been separated. This is true for SFX layer and _especially_ the voice layer. This has been the case since the new layers were added. I ignored it for Cosmo Memory, but it's far too noticeable with Echo-S to be ignored and further.

**Comment by julianxhokaxhiu** [comment]
Did you double check if the frequency of those files you use externally matches the same being used in the movies?

For eg. I know that some movies do use 22050Hz ( which makes it sound "louder" even this means in reality it has less detail, and therefore depth ).

**Comment by wturner859** [comment]
Both the old Cm fmvs and the current separated audio used 96,000hz. The current voice files are at 48,000hz... Are you saying that in order for these to play at an appropriate volume to the rest of the game (music and sfx) they should be at 22050hz?

**Comment by julianxhokaxhiu** [comment]
No, I'm saying that they must be all at the same frequency, otherwise some resampling will happen and results may vary.

See http://sol.gfxile.net/soloud/concepts.html ( Resampling )

**Comment by wturner859** [comment]
Alright I'll play with the sample rate later today and see if it makes any difference and let you know.

**Comment by julianxhokaxhiu** [comment]
Confirmed it's a bug after some internal testings done by @wturner859

**Comment by julianxhokaxhiu** [comment]
Issue definitely addressed via https://github.com/julianxhokaxhiu/FFNx/commit/c2ce27375b802bc0ec6513718a67531b9b5de1fd
