### ISSUE TITLE
[FF7] OpenGL + Advanced Lighting causes field tile visual glitch

### ISSUE THREAD

**Issue by tangtang95** [julianxhokaxhiu/FFNx#448]
**Describe the bug**
By using OpenGL and Advanced lighting together, visual glitches appear on the field map.

**To Reproduce**

1. Install FFNx 1.12.0.13
2. Enable OpenGL + Advanced Lighting
3. Go to the place shown in the image below to see the glitch

**Screenshots**
![image](https://user-images.githubusercontent.com/5919707/174487490-6945760d-a9e4-4509-93bc-0c0b3731b123.png)

**GPU:**
- Nvidia GTX 1660 Super
- Driver 516.40

**Comment by tangtang95** [comment]
I have tested the latest canary 1.12.0.21, and the bug is still there.

**Comment by julianxhokaxhiu** [comment]
@CosmosXIII should be able to tell us what is precisely not working so we can maybe see where this needs to be fixed properly.
