### ISSUE TITLE
[ FF7 ] External Music loops skipping.

### ISSUE THREAD

**Issue by wturner859** [julianxhokaxhiu/FFNx#452]
Talked about in Discord, but for bug tracking;

It looks like songs are suddenly "skipping" at loop points... songs that previously looped fine and have perfect loop points now have like a .10 second silence at loop points.
Music sync disabled.

**Comment by wturner859** [comment]
[OB.zip](https://github.com/julianxhokaxhiu/FFNx/files/9312601/OB.zip)
Put this song in music folder, start new game, wait 3:11 for the loop.

**Comment by julianxhokaxhiu** [comment]
Thanks for adding a use-case
