### ISSUE TITLE
[ FF7 ] Battle camera control bugs

### ISSUE THREAD

**Issue by tangtang95** [julianxhokaxhiu/FFNx#460]
This is a list of bugs I encountered with battle camera controls. Just for remembering, I list it here so we can check it out.

There are some occasion during the start of the battle, where the camera upon taking control (https://github.com/julianxhokaxhiu/FFNx/blob/master/src/ff7/camera.cpp#L265-L272) it snaps in one frame to another camera position. For example, this can be replicated against the thiefs enemies outside the church of Aerith on the road towards Aerith's house. It's not related to the `abs() < 1`, but maybe it's about this (https://github.com/julianxhokaxhiu/FFNx/blob/master/src/ff7/camera.cpp#L323-L338). What happens if the `battle id` is the same as the previous battle? 

There is also the bug of camera control during the camera end script movement (during fanfare) in the battle against the icicle enemy. 

Also, why https://github.com/julianxhokaxhiu/FFNx/blob/master/src/ff7/camera.cpp#L317 the parameter `cameraFocusPosition` is not used or overwritten?

@CosmosXIII

**Comment by julianxhokaxhiu** [comment]
@CosmosXIII is this bug still valid?

**Comment by CosmosXIII** [comment]
@julianxhokaxhiu Sorry for the very late reply but yes this bug is still valid. I'll do some testing and see if I can fix it.
