### ISSUE TITLE
[ FF7 ] Some of the worldmap Fx are missing (the particles around cloud in forest for example)

### ISSUE THREAD

**Issue by satsukiyatoshi** [julianxhokaxhiu/FFNx#465]
Even with vanilla game + default FFNx settings, some Fx or the WM are not working.
For exemple with FFNx :
https://cdn.discordapp.com/attachments/695390748287303731/992155064154194062/2022-06-30_21-45-36.mp4

In vanilla game (psx capture but it's the same in original pc game):
https://www.youtube.com/watch?v=h0mqRkhOvtY&t=26339s

**Comment by LaZar00** [comment]
For a bit of help, this is a screenshot of the fx in the forest WITHOUT FFNx and original PC 1998 vanilla game with patch 1.02.
![imagen](https://user-images.githubusercontent.com/46090031/177957131-b6c3ad5e-f4fa-47f0-a6d6-78884d259dba.png)
