### ISSUE TITLE
[ FF7 ] Game hangs on startup when using the Vulkan renderer and Borderless window mode is set

### ISSUE THREAD

**Issue by JeffBittle** [julianxhokaxhiu/FFNx#470]
**Describe the bug**
FF7 hangs at a black screen when attempting to start in borderless windowed mode while using the Vulkan renderer, possibly AMD specific.  I don't have an Nvidia card to test with.

**To Reproduce**

1. Set renderer_backend to 5
2. Set fullscreen to false
3. Set borderless to true
4. Run FF7
5. See error

**Expected behavior**
Would expect the game to start and run in a borderless window with the Vulkan renderer.

[FFNx.log](https://github.com/julianxhokaxhiu/FFNx/files/9208312/FFNx.log)

**GPU (please complete the following information):**

- AMD Radeon RX 480 8GB
- Driver Version
22.20.15.01-220725a-381283E-AMD-Software-Adrenalin-Edition

**Additional context**
This is the FFNx log taken with renderer_debug enabled at the time
[FFNx.log](https://github.com/julianxhokaxhiu/FFNx/files/9208312/FFNx.log)

**Comment by julianxhokaxhiu** [comment]
This has been fixed starting Canary 1.13.0.34+
