### ISSUE TITLE
[ FF7 ] Fort Condor targeting not working with external textures

### ISSUE THREAD

**Issue by satsukiyatoshi** [julianxhokaxhiu/FFNx#49]
If you use external textures in for the background in fort condor (the "mapx" files) you can't see the target for the automatic defence placement (even with straight extracted png files without processing)

Vanilla:
![Screen Shot 005](https://user-images.githubusercontent.com/8547498/82754336-89434d80-9dcc-11ea-834b-83eeaa07286b.PNG)

External texture use:
![Screen Shot 004](https://user-images.githubusercontent.com/8547498/82754341-906a5b80-9dcc-11ea-9c87-51a5b71348b3.PNG)

**Comment by julianxhokaxhiu** [comment]
Fixed in the latest canary. Feel free to try :)
