### ISSUE TITLE
[ FF7 ] Strange behaviour with a looping/non-stop sound in background using MIDI Standard + Cosmo Memory

### ISSUE THREAD

**Issue by LaZar00** [julianxhokaxhiu/FFNx#495]
**Describe the bug**
There is an odd "loop" (or the sound does not stops) of the wind sound in specific scenes. This happens only with MIDI Standard + Cosmo Memory mod. I tried it running ONLY FF7.EXE with FFNx (without 7H) and this happens also (I copied the sound files from Cosmo Memory like UI sounds and music/vgmstream).
At least in 2 scenes happens this issue.
One scene is when Temple of the Ancients shrinks (jtemplb-601):

**Discord explanation**: https://discord.com/channels/318179907098116106/613051825863524365/1018200984574496778
**Video (Temple of the Ancients)**:
https://discord.com/channels/318179907098116106/613051825863524365/1018200924881162251
**Video (Prof. Gast lab)**:
https://discord.com/channels/318179907098116106/613051825863524365/1018978240355913759

**To Reproduce**
1. You must have configured FF7 for playing MIDI Music and using Cosmo Memory (if using 7H).
2. Play some of the previous scenes mentioned.

**Expected behavior**
You will see the loop of the wind sound (in the first Temple of the Ancients scene) or the wind sound does not stops (in the Video of Prof Gast lab).

**Additional context**
I have checked without Cosmo Memory (with MIDI Music) and it works perfectly.
I have checked with Cosmo Memory and VGMStream Music and it works perfectly.

**Comment by LaZar00** [comment]
More Info. Strange as it seems, the snowboard minigame (at least the story snowboard minigame) suffers also from this wind loop after finishing the minigame.

**Comment by LaZar00** [comment]
Supposition. What happens when the MUSIC opcode is called in a script for playing a song (snow.mid -Buried in the Snow-) if previously we have called another MUSIC opcode (0xF0) that must play a sound (wind.wav/wind.ogg -in CM-)? It is only a thought. FFNx does something with that opcode?
- It stops the previous sound or song?
- It should stop the playing only if the previous play is a sound? (in fact we have a music.idx file in "data\music" and the 4 .wav sounds with that names...)
Mmm....

**Comment by LaZar00** [comment]
Some more info:
- In Gaea's Cliff this is very easy reproducible because the wind sound sounds almost always, mostly in the latest places of the cliff.
- Even doing a CTRL+R (reset game), the wind loop glitch don't stops, and sounds always.

**Comment by LaZar00** [comment]
Ok, the issue has been solved. You can close this bug.

**Comment by julianxhokaxhiu** [comment]
May I ask how?
