### ISSUE TITLE
[ Core ] HEXT improvements

### ISSUE THREAD

**Issue by shikulja** [julianxhokaxhiu/FFNx#496]
Ignore empty addresses
518370=
518370 = #Comment

Ability to comment on each line
5183D4 = 28 45 78 FF #Comment
5183D4 = 28 45 78 FF {Comment}

This affects efficiency, but for modern PCs this is negligible.

It is necessary for a convenient and compact type of comments, especially if there are a lot of addresses.

Now it looks like this:

#comment1
address1 =

#comment2
address2 =

in this form, the number of lines is much larger, and it is more difficult to count them without comments. It is also more difficult to insert from exel spreadsheets.

Tables when copied look like this:

#Poison	51D246 = 	30 4F 49 53 4F 4E FF
51D246 = 	30 4F 49 53 4F 4E FF	#Poison

that is, it now requires a shift to NewLine if the comment is at the beginning of a line. Or manual editing if the comments are at the end of the line.

**Comment by julianxhokaxhiu** [comment]
To be honest, after an afterthought on this I won't implement it as it's outside the spec provided by DLPB. I followed that one to implement the Hext support and I don't want to go custom with this layer. I have other ideas regarding this layer overall so for now you'll have to live with the usual way to comment :) Sorry!
