### ISSUE TITLE
[ FF7 ] Audio skipping at a track's loop point

### ISSUE THREAD

**Issue by SpyroChris** [julianxhokaxhiu/FFNx#497]
There is a strange issue that occurs when certain tracks that are over 2.5 minutes long get looped back to their LOOPSTART point.

**To Reproduce**

1. **CHOOSE THE "Play without mods" option from the upper left corner on 7th Heaven with VGMStream option enabled**, then simply load any file in the overworld after Meteor is summoned in Disc 2 such as this one: https://drive.google.com/file/d/19HoyIHcLQ41LlIIvI4d3lcF8BwCvqTLq/view?usp=sharing
2. Open up the first slot
3. Wait for at least 3 minutes and 6 seconds (that is where the loop point of "kita.ogg" is at)
4. The audio should skip/buzz and loop back to the LOOPSTART point, just like in the following video: (https://drive.google.com/file/d/1GuZrXEbNkfLsMO3EaafKSKhWqCtVG7tv/view?usp=sharing) **at 00:10**

Specs
CPU: i7-10870H
RAM: 16GB DDR4
GPU: RTX 3060

Resolution 1920x1080
Widescreen on
Internal resolution *4
Antialiasing: off
Antisotropic: on
Vertical sync: on
7th Heaven version: 2.6.1.21
FFNx version: 1.13.0.79

Also tested on specs: 
CPU: i7-3820
RAM: 16GB DDR3
GPU: GTX 1070

Resolution 3840x2160
Widescreen OFF
Internal resolution *4
Antialiasing: off
Antisotropic: on
Vertical sync: on
7th Heaven version: 2.6.1.21
FFNx version: 1.13.0.79

**Comment by julianxhokaxhiu** [comment]
I was finally able to locate where the bug is, and it lives this time within the VGMStream library itself.
