### ISSUE TITLE
[Common] Add alt+enter combo to toggle fullscreen mode

### ISSUE THREAD

**Issue by shikulja** [julianxhokaxhiu/FFNx#53]

**Comment by Extapathy** [comment]
Since we've hooked the WindowProc function now, code similar to the following should be able to process the key:
```
if (uMsg == WM_KEYDOWN || uMsg == WM_SYSKEYDOWN) {
	if (wParam == VK_RETURN && (HIWORD(lParam) & KF_ALTDOWN)) {
		ToggleFullscreen();
		return 0;
	}
}
```

The main problem is actually implementing the resolution change and updating all the states.

**Comment by julianxhokaxhiu** [comment]
Yep, this now a possibility thanks to your implementation :) Should be rather trivial to be implemented. I'll definitely look into it as soon as I finish the vcpkg integration!

**Comment by julianxhokaxhiu** [comment]
Feature available on the latest canary :)

**Comment by julianxhokaxhiu** [comment]
Reopening because OpenGL seems to crash and some fixes are required to be done ( like the rendering seems to be too smooth )

**Comment by shikulja** [comment]
alt and win stop working, when ff8 runing
FFNx v1.7.2.38.zip (FFNx-v1.7.2.104)

**Comment by julianxhokaxhiu** [comment]
Allright, the feature is now complete and everything should be there for a daily gameplay :) Feel free to try the latest canary

**Comment by shikulja** [comment]
alt + (tab) and win key Locked, unable to switch between windows

**Comment by julianxhokaxhiu** [comment]
I'm able to do both the actions here. Windows 10 2004 ( May 2020 ) release. If you could provide a more detailed info on the environment you use maybe we can try to check what is going on...thanks.

**Comment by shikulja** [comment]
> I'm able to do both the actions here. Windows 10 2004 ( May 2020 ) release. If you could provide a more detailed info on the environment you use maybe we can try to check what is going on...thanks.

win10 x64 2004. nothing special

**Comment by julianxhokaxhiu** [comment]
Something else is preventing that, if you can join Qhimm Discord or Tsunamods Discord on FFNx dedicated channels, you'll see other users did try the same and it's working fine for them. I'd say try please the latest canary and let's see how it goes.

**Comment by shikulja** [comment]
@julianxhokaxhiu 
no, this is definitely not something else.
When I run ff8 (ffnx) alt + tab and win key stop working. And not vice versa. Well, if it works for others, perhaps an exceptional case, well, if I said something, suddenly someone will have the same problem.

**Comment by julianxhokaxhiu** [comment]
Ah here's the thing! You never specified the game and I took FF7 as default. I forgot you were speaking about FF8 and yes, I am able to get the same issue :) Thank you for letting me know that. I'll see what I can do about it.

**Comment by julianxhokaxhiu** [comment]
Ok sorry, tested also the latest stable and this is not a related issue. This has been a thing since forever and has to be tackled in a separate issue. Closing this forever. Please make sure you try this on stable releases too in order to avoid the confusion. Thank you!
