### ISSUE TITLE
[ Common ] x264 FMV Range Horkage

### ISSUE THREAD

**Issue by ChthonVII** [julianxhokaxhiu/FFNx#533]
[Edit: Pretty sure it's actually a gamma decoding bug, as described in the third post down.]

**Describe the bug**
I'm getting incorrect colors when playing back FMVs with x264 video streams (e.g. SYW's upscales). It appears that a TV->PC range conversion is being done _TWICE_ on playback, regardless of whether the video is flagged as full range or TV range. Videos in question are yuv420p10le; I haven't tested the behavior with 8-bit video yet.

[Edit: On second thought, since there does not appear to be anywhere in the FFNx screenshot that's brighter than the vseditor screenshot, it's probably not a double TV-PC range conversion. It's probably a gamma problem.]

**To Reproduce**
1. Start a new game and play the Opening FMV from SYW's upscales mod.

**Expected behavior**
TV->PC range conversion should be done once if the video is flagged is TV range, or zero times if the video is flagged as full range.

**Screenshots**
Screenshot from FFNx. Note how the darks are all squashed to black.
![wrong](https://user-images.githubusercontent.com/19508863/216249765-bdad1168-5c0f-490f-aef1-f84376d4b7ec.png)

Screenshot from VapourSynth Editor showing correct colors after a single TV->PC range conversion.
![correct](https://user-images.githubusercontent.com/19508863/216249773-6bc6be26-4c08-43e7-94ea-73269198eee5.png)

**GPU (please complete the following information):**

- Brand: Nvidia GeForce GTX 1080
- Driver Version: 470.161.03
- Note: Linux user. It's unlikely a newer driver will ever be available for this GPU.

**Workaround**
Colors look close to right if I re-encode the video while using vapoursynth to further squash the range with an extra PC->TV range conversion applied to already-TV-range video. This is maybe sorta kinda acceptable for 10-bit video since the doubly-squashed range is still bigger than what the typical 8-bit monitor can display. However, re-encoding _all_ of the FMVs would be a major pain in the arse. [Edit: Close but not quite. It looks like the gamma is off too. I'll have to figure out how to encode some test bars so I can measure the error.]

**Additional context**
VLC exhibits a similar bug. Of the various test videos that FFNx displays incorrectly, VLC displays some of them correctly and some of them incorrectly. (By comparison, mpv gets them all correct.) [This VLC bug report](https://code.videolan.org/videolan/vlc/-/issues/19723) looks like _maybe_ it might be related. A commenter there suggests that Nvidia's hardware decoding might be at fault. If that is correct, then perhaps an option to use pure software decoding might solve the problem.

**Comment by ChthonVII** [comment]
Yep, it looks like that's it exactly. In /src/video/movies.cpp, ffmpeg is never asked to fetch the transfer metadata. And then, in misc/FFNx.common.sh, the srgb transfer curve is used to decode gamma. Which is wrong because the gamma encoding was almost certainly done with the SMPTE170M transfer curve (shared by rec601 and rec709) in the first instance.

So the fix is:

Add this function to misc/FFNx.common.sh:
```
vec3 toLinearSMPTE170M(vec3 _rgb)
{
	bvec3 cutoff = lessThan(_rgb.rgb, vec3_splat(0.081));
	vec3 higher = pow((_rgb.rgb + vec3_splat(0.099)) / vec3_splat(1.099), (vec3_splat(1.0) / vec3_splat(0.45)));
	vec3 lower = _rgb.rgb / vec3_splat(4.5);

	return mix(higher, lower, cutoff);
}
```

Then on line 96 of /misc/FFNx.frag, replace
`color.rgb = toLinear(color.rgb);`
with
```
if (isMovie){
	color.rgb = toLinearSMPTE170M(color.rgb);
}
else {
	color.rgb = toLinear(color.rgb);
}
```

And then make the same change on line 116 of misc/FFNx.lighting.frag.

**Comment by julianxhokaxhiu** [comment]
Thanks for the research and knowledge share. Care to make a PR? :) I'll be happy to review, thank you!

**Comment by ChthonVII** [comment]
I put in a PR. Unfortunately, I don't have a suitable Windows build environment readily available, so it's totally untested.

I noticed some other colorimetry issues along the way. I'll try to write them up.

**Comment by julianxhokaxhiu** [comment]
Thanks a lot

**Comment by julianxhokaxhiu** [comment]
Closing in favor of #536
