### ISSUE TITLE
[ Common ] Incorrect Full-Range YUV->RGB Conversion

### ISSUE THREAD

**Issue by ChthonVII** [julianxhokaxhiu/FFNx#535]
On line 88 of FFNx.frag and line 108 of FFNx.lighting.frag (1.0/16.0) is subtracted from y. This is correct for TV-range rec601 yuv->rgb conversion, but incorrect for full-range. For full range, y should be left as is. Therefore, this subtraction needs to be made conditional on !isFullRange.

[Edit: This bug is sorta compensating for another bug on line 241 of movies.cpp where both source and destination range are set to full range, resulting in no conversion happening. Source range should be set to TV. [Further Edit: Sorry. Source range should be set to whatever the video stream says it is. Something like yuv420p10le might be tv- or full-range, so we can't assume.]]

Relatedly, the correct matrix values vary depending on who you ask. When I find time, I'll recompute them from the spec document.

**Comment by julianxhokaxhiu** [comment]
Closing in favor of #536
