### ISSUE TITLE
Game Crashes on startup

### ISSUE THREAD

**Issue by SpikerzZ406** [julianxhokaxhiu/FFNx#539]
it was working yesterday no problem, played today and now I get an error when starting the game

"Feel free to visit this link to know about further next steps you can take
https://github.com/julianxhokaxhiu/FFNx/blob/master/docs/faq.md"

All I did was update from 1.15.0.1 to 1.15.0.12, I then tried to revert the update back and still not working
I attached the log file

[FFNx.log](https://github.com/julianxhokaxhiu/FFNx/files/10687027/FFNx.log)

**Comment by eve-atum** [comment]
Sounds like you may have had a Windows patch cause a reboot overnight, and in true MSFT fashion, they've changed security settings without your knowledge or consent.  If you're on either the Qhimm or Tsunamods discord, issue the "/dep" command in one of the FF7 support channels to see how to check (and possibly revert) that setting.

**Comment by SpikerzZ406** [comment]
Thanks for the help, while I was waiting for a response I uninstalled FF VII and deleted the folder, then reinstalled it with FFNX version 1.15.0.0 and now it is working again
