### ISSUE TITLE
[ FF7 ] Snow footsteps not shown in Worldmap (Icicle Area)

### ISSUE THREAD

**Issue by LaZar00** [julianxhokaxhiu/FFNx#550]
I was doing some testing with textures of worldmap and I found this issue. After some research, I've seen in youtube videos that the PSX version of FF7 and the PC vanilla version of FF7 (without FFNx) shows the marks of the footsteps of Cloud when walking in the worlmap, specifically, in the Icicle Area.

I can confirm this is true by myself and running FF7 without FFNx.

To reproduce you must go to Icicle Area and walk over the snow.

I include 2 videos, the first is with vanilla game (NO FFNX):

https://user-images.githubusercontent.com/46090031/223786603-7264b0f6-bf64-4fc5-a159-19379615685b.mp4

This second video is with the latest version of FFNx (embed in the video) and WITHOUT any mod:

https://user-images.githubusercontent.com/46090031/223786763-0ef53d85-b479-4f5a-ae87-55fa43c5c19b.mp4

**Comment by julianxhokaxhiu** [comment]
Reminds me of https://github.com/julianxhokaxhiu/FFNx/issues/465

Nice finding though, I'll see if I can find some time this week to investigate it.

**Comment by LaZar00** [comment]
It seems very odd. Normally this specific textures (like the vapour of Highwind engines when flying or effect while walking among the forests) are in world lgp, texture dfx.tex. But I'm not sure, this time I have not checked what is happening here.
