### ISSUE TITLE
[ FF7 ] Widescreen Should Be Force Disabled for the Honeybee Inn Keyhole Scenes

### ISSUE THREAD

**Issue by ChthonVII** [julianxhokaxhiu/FFNx#558]
**Describe the bug**
The Honeybee Inn keyhole scenes don't display properly when widescreen is enabled. The black texture with the transparent keyhole in the center does not extend to cover the widescreen areas.

**To Reproduce**
Steps to reproduce the behavior: Enable widescreen, view those scenes. 

**Expected behavior**
Widescreen should be force disabled for these scenes so they display correctly.

**Comment by julianxhokaxhiu** [comment]
Please do not open other tickets for Widescreen, this is a feature being worked on and is tracked at #474 Thank you.
