### ISSUE TITLE
[Common] PNG loading is a lot slower than Aali's original OpenGL driver

### ISSUE THREAD

**Issue by DLPB2** [julianxhokaxhiu/FFNx#56]
Likely to do with new implementation.  DDS is very good.

**Comment by julianxhokaxhiu** [comment]
Thanks. That's caused by internal PNG library used by BGFX known as lodepng ( https://github.com/bkaradzic/bimg/tree/master/3rdparty/lodepng ).

I already approached the author to know if there's a way to swap it with libpng instead.

**Comment by julianxhokaxhiu** [comment]
So I managed to work on the overall Texture memory management as well as the PNG layer ( https://github.com/julianxhokaxhiu/FFNx/commit/75ee0b17bddbdd98956980d71890d63aaf66310b ).

Through the combination of these two, I managed to improve the timings which were tested by @satsukiyatoshi and reported as improved.

Can you please check yourself too? Just download the latest canary.

Ty
