### ISSUE TITLE
[ FF7 ] Resolution dropdown box only shows resolutions for Monitor 1

### ISSUE THREAD

**Issue by PhoenixEnema** [julianxhokaxhiu/FFNx#562]
**Describe the bug**
![image](https://user-images.githubusercontent.com/127917788/230654171-601e2eff-587d-48da-8cfc-513bf9efdb69.png)
![image](https://user-images.githubusercontent.com/127917788/230654280-7fc7e6f1-3792-43c8-a74c-4ccacfda17b5.png)
In multi monitor setups, the resolution dropdown only shows the resolutions available for monitor 1. In my setup, my main display is only able to be connected to the 2nd port, normally not an issue, but since my secondary monitor is old, my resolution choices are very limited, and resizing the window causes things to lock up.

**Comment by julianxhokaxhiu** [comment]
This has nothing to do with FFNx. Not sure which launcher you're using but you need to report this to the author of that launcher.
