### ISSUE TITLE
[ FF8 DE NV ] Cannot enter worldmap

### ISSUE THREAD

**Issue by myst6re** [julianxhokaxhiu/FFNx#565]
**Describe the bug**
The game hang when entering worldmap. Not logs, no crash. The wmx file opening seems the last known step.
This is happening only with DE nvidia patch.

**To Reproduce**
Enter the worldmap with DE nvidia patch.

**Additional notes**
I disabled vram and worldmap modules, and the bug is still there.

**Comment by julianxhokaxhiu** [comment]
I'll try to investigate it here and if I find anything I'll let you know.

**Comment by myst6re** [comment]
Oh no I found why: hext loads hext/ff8/de and not hext/ff8/de_nv
I add this fix on my next PR
