### ISSUE TITLE
[ COMMON ] Massive Performance Degradation

### ISSUE THREAD

**Issue by ChthonVII** [julianxhokaxhiu/FFNx#578]
**Describe the bug**
Some commit later than b6bf503 and not later than f7cb728 is causing massive performance degradation. Though aging, my PC can handle 60fps at 4k with [this branch](https://github.com/ChthonVII/FFNx/tree/fmvgammafix) including commits through b6bf503 plus my FMV & color stuff. But it often falls as low as 30fps when that branch is rebased on top of commits after b6bf503. For example, the Hell House's Suicide Drop skill dips my fps as low as 30.

**Comment by julianxhokaxhiu** [comment]
I'd need some more feedback on this one, if anyone wants to try I'd appreciate.

A quick way to test this is downloading v1.15 stable vs canary.

Thank you in advance.

**Comment by ChthonVII** [comment]
I'm not having the same issue with the most recent canary.

This suggests that it's caused by something in my build environment. I've got a theory, but it will take awhile to check out. I'll report back.

**Comment by ChthonVII** [comment]
Looks like this was a vcpkg issue. See [notes here](https://github.com/julianxhokaxhiu/FFNx/issues/577#issuecomment-1630322438).

**Comment by julianxhokaxhiu** [comment]
Thanks, I'll close this one in favor of #577
