### ISSUE TITLE
[Common] OpenGL Green lines while rendering on Intel GPUs

### ISSUE THREAD

**Issue by shikulja** [julianxhokaxhiu/FFNx#62]
https://github.com/julianxhokaxhiu/FFNx/issues/60

in steam version the same

(stop me talking about legality, I'm licensed in steam), pc2000 I can't play without a cd drive. because I don't have one. L-logic, so this bug and without cdfix is also repeated)
[FFNx.log](https://github.com/julianxhokaxhiu/FFNx/files/4740051/FFNx.log)

I'm just trying to help fix a mistake, why i don't understand.

**Comment by shikulja** [comment]
forgot enable dubug
[FFNx.log](https://github.com/julianxhokaxhiu/FFNx/files/4740070/FFNx.log)
![Аннотация 2020-06-06 161017](https://user-images.githubusercontent.com/3386359/83944995-42b01300-a810-11ea-88e1-3fb144818fe9.png)

**Comment by julianxhokaxhiu** [comment]
It looks like to me an issue on your end. I don't think it's related to FFNx only. Does this happen also on vanilla Steam? I did try to replicate also my Steam installation on top of the Intel GPU and it doesn't happen. If you own a copy of FF7, do try FFNx there too and let me know if you see the same green lines.

Thank you.

**Comment by shikulja** [comment]
clean vanilla ff7 log
[FFNx.log](https://github.com/julianxhokaxhiu/FFNx/files/4740074/FFNx.log)


![Аннотация 2020-06-06 161239](https://user-images.githubusercontent.com/3386359/83945131-337d9500-a811-11ea-8f1c-cfafdf872b22.png)
![Аннотация 2020-06-06 161654](https://user-images.githubusercontent.com/3386359/83945133-34aec200-a811-11ea-87e8-d4ce8dbdf04e.png)

**Comment by julianxhokaxhiu** [comment]
Thank you. I'll double check on my side and let you know.

**Comment by julianxhokaxhiu** [comment]
Current workaround: use `Direct3D11` instead of OpenGL

**Comment by shikulja** [comment]
> Current workaround: use `Direct3D11` instead of `OpenGL`
I do, so it's not a critical mistake, just for the future.

**Comment by shikulja** [comment]
OpenGL green bug on FFMpeg Videos on Intel GPUs
it's not an FFMpeg bug - it's a renderer bug

![Аннотация 2020-06-06 163542](https://user-images.githubusercontent.com/3386359/83945514-ca4b5100-a813-11ea-8c07-f8772cd38839.png)

**Comment by julianxhokaxhiu** [comment]
Yeah I was finally able to replicate it here too. It's an overall rendering bug, which may be also driver related. I'm not sure if I'm able to do anything about it, but I'll check.

**Comment by julianxhokaxhiu** [comment]
So this seems to be a core BGFX issue as I'm able to replicate the very same thing on the provides demos. I'll check with the lib author how we can fix this.

![image](https://user-images.githubusercontent.com/1237070/83950262-b6aae500-a829-11ea-82eb-6aa95603d573.png)

**Comment by julianxhokaxhiu** [comment]
Please try the latest canary. This issue should now be fixed. Thanks again for the report!

**Comment by shikulja** [comment]
> Please try the latest canary. This issue should now be fixed. Thanks again for the report!
Work. Fixed.  (gamepad works too, but no vibration, )
![Аннотация 2020-06-07 141248](https://user-images.githubusercontent.com/3386359/83967329-13111180-a8c9-11ea-892a-2cd93c21e919.png)

**Comment by julianxhokaxhiu** [comment]
Great, thank you :) There's no Vibration support in general as far as I know. In case I'll open an issue in case this deserves a fix. Cheers!
