### ISSUE TITLE
[ Final Fantasy VII Steam ] Steam Achievements do not work on Steam Deck with FF7_SYW_Unified Mod

### ISSUE THREAD

**Issue by Rot-gut** [julianxhokaxhiu/FFNx#631]
**Describe the bug**
Steam achievements do not work when playing FFVII with FF7_SYW_Unified installed and FFNx "Steam Achievements" toggle enabled.

**To Reproduce**
Install FF7 on Steam Deck.

Since the installer can't view the .local directory, create a symbolic link to the folder containing the FF7 executable in one of the folders in your Home directory:

0. Download the latest SYW Unified Mod: https://forums.qhimm.com/index.php?topic=21616.0
1. After installing the game, right-click on it, select Manage, and Browse local files to find the location of the folder.
2. Open a new tab in your file explorer and go to the Home directory or a subdirectory within the Home directory.
3. Right-click > Create new > Link to a file or directory...
4. Give your link a name and paste the path of the folder you opened just before.
5. Install Lutris (available in the Discover store):
6. Run Lutris, click the + button, and then Add a locally installed game.
7. Name your game and select Wine from the Executor dropdown menu.
8. Go to the Game Options tab, Browse, and locate the pack's installation executable, then click Save.
9. Go to the Wine Prefix field and identify a folder for the installation such as /home/deck/FF7_SYW_Unified then click Save.
10. Click on your game, and at the bottom of the window, click the wine glass icon, then select Winetricks. A new window appears in the taskbar, click on it.
11. Leave the option on "Select the default wineprefix" and click Validate. Another window appears in the taskbar, click on it.
12. Select "Install a Windows DLL or component" and click Validate. Another window appears in the taskbar, click on it.
13. Select dotnet48 and click Validate.
14. You should now be able to run the installer from Lutris without any issues and point it to the executable of your FF7 game installed on Steam.
15. Once the game is installed, right-click on your game in Lutris and click Configure:
16. Modify the location of the executable, select the update, and repeat the process to install it.
17. After the update is installed, right-click on your game in Lutris and click Configure.
18. Change the location of the executable and select the game's executable: FF7_SYW_Unified.exe, and save your changes.
19. Right-click again on the game, then click Create Steam shortcut.
20. Switch to Gaming Mode and run the game. Remember to adjust your controller profile to support the mouse; it will be much more convenient than using touch controls.
21. Launch the game from the mod's configuration menu and exit.
22. Return to Desktop mode, delete the Steam shortcut.
23. In Lutris, right-click on your game, then Configure, and once again modify the executable location to use: Pack installation folder /Game/FF7.exe so that the game runs directly without going through the configuration menu.
24. Right-click again on your game > Create Steam shortcut.
25. Launch the game from Gaming Mode.
26. Try to get an achievement (won't unlock).

**GPU (please complete the following information):**

- AMD Steam Deck OLED GPU
- (Not sure where to find this)

**Additional context**
satsuki recommended this issue be reported to FFNx: https://forums.qhimm.com/index.php?topic=21616.msg289896#msg289896

**Comment by julianxhokaxhiu** [comment]
This is not a bug for FFNx, you need to report this on the original author mod support channel. Cheers!
