### ISSUE TITLE
[ Core ] Auto HDR support on Windows 11

### ISSUE THREAD

**Issue by TimberAngry** [julianxhokaxhiu/FFNx#640]
## Summary

On the list of user features on the front page, it lists 'HDR Support' (which is quite vague, suggest to update this for clarity), but I was surprised to find that Auto HDR doesn't seem to activate on Windows 11, even though there is a DirectX11/12 APIs available in the driver.

### Basic example

I looked around for a workaround and found this information:
https://www.pcgamingwiki.com/wiki/Glossary:High_dynamic_range_(HDR)#Enable_HDR_output_in_unsupported_games

For me, setting the game to Vulkan and then adjusting the Nvidia options did the trick.

### Motivation

Just wanted to make a feature request here as I thought maybe with some tweaks the DirectX11/12 modes of the driver could enable HDR naturally, and more people could enjoy these games in HDR :)

**Comment by julianxhokaxhiu** [comment]
HDR is already supported natively and there's no need for Auto HDR, which is a feature to bring HDR on game that do not support it natively. At the moment HDR works only on DirectX 12 so make sure your system has HDR enabled while using that backend and you'll be good to go. If for some reasons color feel flashy, you might want to tweak the [hdr_max_nits ](https://github.com/julianxhokaxhiu/FFNx/blob/master/misc/FFNx.toml#L146) configuration up to your pleasure.

**Comment by TimberAngry** [comment]
Thanks for the info that's good to know, I tried using DX12 but the screen freezes a lot (can still hear sound and controls are working, but nothing moving on screen). Vulkan has crashing issues for me too, so I had to fall back to OGL and use this workaround. Just adding this comment here in case it helps someone.
