### ISSUE TITLE
[ Common ] Add an option to overide save files folder

### ISSUE THREAD

**Issue by satsukiyatoshi** [julianxhokaxhiu/FFNx#66]
For easyer mod management it would be cool to be able to overide save folder (as already done for hext for exemple) as an option in cfg file

Thanks

**Comment by julianxhokaxhiu** [comment]
Feel free to try the last canary :) Look for `save_path`

**Comment by satsukiyatoshi** [comment]
Working but don't support subfolder use nor special chars.
-save_path = "save2" -- Working
-save_path = save2 -- working
-save_path = savé2 -- not working
-save_path = "savé2" -- not working
-save_path = mods/gameplay/moddetest01/ -- not working
-save_path = "mods/gameplay/moddetest01/" -- not working

**Comment by julianxhokaxhiu** [comment]
Related to the wrong path: that is now fixed, I had some poor logic check to handle if I already overrode the path, but now it should be fine.

Related to special chars: unfortunately the code is not (yet) Unicode ready, but it will be hopefully one day :) See #31
