### ISSUE TITLE
[FF7 Steam] Corrupted ff7input.cfg

### ISSUE THREAD

**Issue by petfriendamy** [julianxhokaxhiu/FFNx#677]
Sometimes, with FFNx installed, the ff7input.cfg file will get corrupted, overwriting all of the user's keybinds and replacing them with what seems to be some sort of default controls on the numpad. The speedrunning community has found a consistent way to reproduce this behavior:

1) Start a new game
2) Enter the config menu (it does not seem to matter if you change any settings)
3) Exit the config menu
4) Doing this will create the corrupted ff7input.cfg file

Multiple users have reported this behavior.
[ff7input (corrupt).cfg.zip](https://github.com/julianxhokaxhiu/FFNx/files/14725195/ff7input.corrupt.cfg.zip)

**Comment by julianxhokaxhiu** [comment]
Can you please confirm if you're able to repro the issue since we merged #683 ? Thanks!

**Comment by petfriendamy** [comment]
Looks like it's been fixed, thanks!
