### ISSUE TITLE
[ FF7 ] Adding new facial expression to NPC models doesn't update the blinking animation.

### ISSUE THREAD

**Issue by Bjburn2689** [julianxhokaxhiu/FFNx#691]
When adding new "eye_[Model ID]_2" and "eye_[Model ID]r_2" textures to an NPC character model (e.g. eye_BBAB_2 and eye_BBABr_2) the eye on the model are updated to use the new textures when the second eye setting is called using the Kawai code, but when using the game's blinking system the NPC character models still default to Cloud's closed eye textures instead.

**To Reproduce**

1. Go to the face test menu in the Shinra Archaeology debug room.
2. Select Cloud so the other models load in properly.
3. Go back.
4. Choose "NPC" from the menu. 
5. Choose "Eyes 2" from the menu. (this updates the eyes using the Kawai code, the textures that appear is how it _should_ look).
6. Choose "Eyes 1" from the menu.
7. This will be hard to see because of how short the blink animation is, but after selecting "Eyes 1" the model will blink before reverting to the default open-eye setting. The blinking eyes will be Cloud's closed eyes rather than the custom closed eye textures that should appear.

**Expected behavior**
The custom eye_[Model ID]_2 and eye_[Model ID]r_2 textures should appear both when the model is blinking and when Kawai code is used.

**Screenshots**
![image](https://github.com/julianxhokaxhiu/FFNx/assets/55000539/7412ffa5-0263-4317-bdb1-73bbb4311b37)
When model is blinking

![image](https://github.com/julianxhokaxhiu/FFNx/assets/55000539/b426740f-9644-43ce-944d-0b47be26b5cc)
When Kawai code is used

**Additional context**
This is not a problem for the party member character models because the game has special cases for them.

**Comment by julianxhokaxhiu** [comment]
Fixed by https://github.com/julianxhokaxhiu/FFNx/commit/f8b322f42e5ef62d7079f4fce7aee065c9fc0f98 - make sure you provide the custom eye textures for the eye index 1 ( eg. `eye_BBAB_1.TEX`, `eye_BBABr_1.TEX` )
