### ISSUE TITLE
[ FF8 ] Transparency appears really dark when using custom background textures

### ISSUE THREAD

**Issue by kayleewright-bluescape** [julianxhokaxhiu/FFNx#693]
**Describe the bug**
When using custom background textures (even ones dumped directly from the game using save_textures = true), the transparency (alpha?) on things like the elevator or transparent screen that Ellone talks to squall through in the intro are much darker than default.

**To Reproduce**

1. Set save_textures = true and start a new games
2. After the doctor talks to Squall and the girl appears on screen take a screenshot
3. Once you have full control go down the elevator outside the classroom and after you step out take another screen shot.
4. Set save_textures = false and start a new game.
5. Repeat 2 + 3
6. Compare both screenshots

**Expected behavior**
Screenshots are identical

**Actual behavior**
Screenshots appear to to be identical except for the transparent surfaces.

**Screenshots**
![FF8 no custom textures](https://github.com/julianxhokaxhiu/FFNx/assets/55107376/959034aa-0750-4487-b248-6139479462c7)
![ff8 custom textures](https://github.com/julianxhokaxhiu/FFNx/assets/55107376/e6629aa0-e101-4e6d-a580-91be082916b5)

**GPU (please complete the following information):**
- NVIDIA
- driver 551.86
- driver 552.44

**Additional context**
- tested with 1.19.1.0
- mcdingus' patreon angelwing textures showed the same issue.
- I tried the latest canary - 1.19.1.34 which showed the same issue with dumped textures (pixel perfect)
- 1.19.1.34 with mcdingus' textures were worse than 1.19.1.0 as they turned pitch black where there should be transparency.

**Comment by julianxhokaxhiu** [comment]
cc @myst6re

**Comment by myst6re** [comment]
> **Expected behavior**
> Screenshots are identical

Yes but we need to check which one is accurate comparing to the original rendering (on PSX), I'm not even sure that the FFNx without mods is correct.

I recently modified a sub related to that (available in the last canary), because on my machine it was not transparent anymore since the last release.

I will take a look, thanks for the report!

**Comment by kayleewright-bluescape** [comment]
Did a little digging and I found this:
PSX (via youtube since I can't pull from my psx):
![image](https://github.com/julianxhokaxhiu/FFNx/assets/55107376/5e6e80fa-a168-4da2-9f8e-c881b0d1e4b6)

Remastered Steam:
![20240513161108_1](https://github.com/julianxhokaxhiu/FFNx/assets/55107376/54a7527e-29b1-44e7-9973-b6a92084cf83)

2013 steam no ffnx:
![20240513162119_1](https://github.com/julianxhokaxhiu/FFNx/assets/55107376/78336aa3-bf8c-4eed-8734-4d7ec1de3a14)

So it sort of looks like ffnx is rendering accurate to the base 2013 steam version but that itself was wrong compared to psx (which got fixed in the remaster).  Which is somewhat closer in ffnx once you start using custom textures (???).

**Comment by Hazado** [comment]
Found a spot this goes completely dark right at the start of the game.

No custom texture
![image](https://github.com/user-attachments/assets/d452625f-74d8-44ca-8375-78cecd2e3e29)

Dumped texture
![image](https://github.com/user-attachments/assets/a2143025-d866-489e-9b10-07c105ee7f76)
