### ISSUE TITLE
[ FF8 ] Issue with the intro sequence looping on the Squaresoft logo

### ISSUE THREAD

**Issue by htp314** [julianxhokaxhiu/FFNx#710]
When starting the game, if you don't skip it, the FF8 intro sequence with the credits and various photos will not play, instead it continuous loops the Squaresoft logo. This happens with or without mods. 

The music plays as normal, but the pictures only loops the Squaresoft logo. It's supposed to show the intro credits with various black and white pictures of the characters from the game.

**Comment by julianxhokaxhiu** [comment]
Can you please post the `FFNx.log` file?

**Comment by htp314** [comment]
[FFNx.log](https://github.com/user-attachments/files/15957354/FFNx.log)

**Comment by myst6re** [comment]
Is it happen with the stable version (1.19.1.0)?

**Comment by htp314** [comment]
No. And it was also working as normal when I used canary version 1.19.1.32. This bug started when I updated to canary v1.19.1.83 or v1.19.1.84

**Comment by myst6re** [comment]
Okay thanks, I will investigate
