### ISSUE TITLE
[ FF8 ] Allow overriding music files per BattleID

### ISSUE THREAD

**Issue by MikeHolmesAudio** [julianxhokaxhiu/FFNx#720]
## Summary
Conditional folder loading tags added to config files.

### Basic example

The below is put within the music file to allow different music to be played with in the laguna sequences, like a different battle theme. This should work with Field ID, Battle ID and Game progress value (PPV). Tsuna said this functionality already exists in FF7. 

<Conditional Folder="Laguna" >
        <RuntimeVar Var="BattleID" Values="180,181,542,129,130,131,132,133,223,224,225,226,227,228,229,230,231,232,233,234,235,122,492,121" />
</Conditional>

### Motivation

This is so we can add musical differences in specific parts of the game for precise timing and functionality, using different versions of tracks in specific battles. Also this would allow the possibility to altering battle sounds and ambience to have echo specifically in caves and other closed spaces

**Comment by myst6re** [comment]
Have you experimented the shuffle attribute?
Something like this (music.toml):

```toml
[cdfield2]
shuffle = [ "bossbat1" ]
```

**Comment by MikeHolmesAudio** [comment]
Where you state [cdfield2] what is that value and where does it come from? In my example I'm trying to replace the win theme in all Laguna battles with an alternate version.

**Comment by julianxhokaxhiu** [comment]
We need to find a way to know when are we in Laguna moment and when in Squall moment. And eventually add this as a variable for lookup in the music name. Something like `win_laguna` or `win_squall` and then if none of those found, fallback to `win` as usual.

The most complex part is how to find when are we on each moment. I haven't had time to look at the field code, maybe there's an OPCODE that lifts a var somewhere between those moments as a signal.

**Comment by MikeHolmesAudio** [comment]
I haven't had a play with Deling yet, but if i can find suitable game progress values, maybe that is a way for us to do it. I can spend some time on that to help the process.

**Comment by myst6re** [comment]
> We need to find a way to know when are we in Laguna moment and when in Squall moment. And eventually add this as a variable for lookup in the music name. Something like `win_laguna` or `win_squall` and then if none of those found, fallback to `win` as usual.
> 
> The most complex part is how to find when are we on each moment. I haven't had time to look at the field code, maybe there's an OPCODE that lifts a var somewhere between those moments as a signal.

I can do that, or we can add a conditional for win relative to the music battle, in field script it is possible to change the music battle for the next battle.

**Comment by myst6re** [comment]
> Where you state [cdfield2] what is that value and where does it come from? In my example I'm trying to replace the win theme in all Laguna battles with an alternate version.

Sorry, it more like [field_cdfield2] and it does not solve your issue

**Comment by MikeHolmesAudio** [comment]
> I can do that, or we can add a conditional for win relative to the music battle, in field script it is possible to change the music battle for the next battle.

Thank you that is much appreciated, is there anything I can do to help? I am super new to coding, I'd like to slowly pick bits up as I go on my modding trip.

**Comment by julianxhokaxhiu** [comment]
> or we can add a conditional for win relative to the music battle, in field script it is possible to change the music battle for the next battle.

My goal is to make it as transparent as possible like we did for FF7. If we can find a way to do so without requiring any game data change I'd appreciate it. Otherwise if we know where this var is all I need is an address and I can take it up from there :) Thanks!

**Comment by MikeHolmesAudio** [comment]
Tsuna just pointed it didn't post my example in the OP. If ifs still useful. This is what we tried.

<Conditional Folder="Laguna" >
        <RuntimeVar Var="BattleID" Values="180,181,542,129,130,131,132,133,223,224,225,226,227,228,229,230,231,232,233,234,235,122,492,121" />
</Conditional>

**Comment by MikeHolmesAudio** [comment]
Tsuna just pointed it out it didn't post my example in the OP, it didn't like the fact it was in text. That's me being a pure noob.
![Screenshot_20240823_194438_Discord](https://github.com/user-attachments/assets/6bd3f447-f88c-439b-8574-c9b9c63eb863)
