### ISSUE TITLE
Shortcut to auto-click text

### ISSUE THREAD

**Issue by HobbitDur** [julianxhokaxhiu/FFNx#725]
It would be nice for testing purpose to be able to auto-validate text with a shortcut. For example, when characters are speaking, the system auto-click X so the box disappear pretty fast without having to mash the button. An exclusion maybe on box with choice ?

**Comment by julianxhokaxhiu** [comment]
For this use case feel free to use [AutoHotkey](https://www.autohotkey.com/). Despite being an easy to add functionality I don't think this makes more sense. It's a very niche case that can be accomplished using other software on top :) Thanks nevertheless
