### ISSUE TITLE
[ FF8 ] Crash when going to after-battle report after killing Gerogero

### ISSUE THREAD

**Issue by Silentwidow** [julianxhokaxhiu/FFNx#726]
**Describe the bug**
Basically the last two times I've tried killing Gerogero/Deling after doing the train decoupling stuff, I get a crash after the battle complete animations finish and it should transition to the after battle report. 

**To Reproduce**
See Above

Expected behavior**
Complete the fight! 

**GPU (please complete the following information):**

- Nvidia 4080
- Driver Version 560.94

[FFNx.log](https://github.com/user-attachments/files/16920771/FFNx.log)

**Comment by julianxhokaxhiu** [comment]
Hello @Silentwidow thanks for submitting the bug report. Are you using custom textures?

**Comment by Silentwidow** [comment]
I believe so, I did notice the gero is red and not blue, I'll try and remove all the textures and try again

**Comment by Silentwidow** [comment]
Renamed the mods folder and tried again and no issues. Not sure why I didn't think to try the most basic of troubleshooting! Thank you.

**Comment by julianxhokaxhiu** [comment]
Glad to hear that. I'll just ping @myst6re in case he wants to troubleshoot this one. Thanks for now :)

**Comment by myst6re** [comment]
The logs say it crashes on a memcpy, maybe the game was exceeded 2 GB in RAM. Currently I see only two solutions:
- patch the game with the 4GB patch
- modify the mod to use smaller images/another pixel format (RGBA for example)
Maybe a possible quickfix on our side is to check if bgfx can allocate data for the texture, currently the helper we use (bgfx::copy) does not let use handle the error.
