### ISSUE TITLE
[ FF8 ] FMV filenames

### ISSUE THREAD

**Issue by AxlRose-RX** [julianxhokaxhiu/FFNx#730]
**Describe the bug**

Using FFNx on both PC2000 and Steam 2013 with `enable_ffmpeg_videos = 1` the file names between the two are completely different and not compatible between each other. This means for a huge file size mod of FMVs, I have to pack twice, one for PC2000 and one for the Steam 2013 where every FMV file name is different between the two, with the exception of `disc04_00h.avi` that is taken and used by FFNx on both game versions (doesn't make sense and leads me to think there might be a bug/typo on the code for the rest of the FMVs)

So far it looks like this:

**On PC2000**           **|**    **Steam 2013**
disc-1_00h.avi    **|**    disc00_00h.avi

While (here this FMV has the same file name on both):

**On PC2000**             **|**    **Steam 2013**
disc04_00h.avi     **|**    disc04_00h.avi

On PC2000 with default `enable_ffmpeg_videos = -1` on the `FFNx.toml`, the game reads the FMVs from CD's .pak file disk1.pak, disk2.pak, disk3.pak and disk4.pak and **ignores** the `install folder\Data\movies`

What is the correct path/`file_name` the PC2000 calls the movies from? I never figured out as different tools give you the option to extract with whatever name you want (but with FFNx log I can track the file and looks like disc-1_00h.avi):

![image](https://github.com/user-attachments/assets/2867e77a-4915-4b19-8387-606bcfd875d6)

![image](https://github.com/user-attachments/assets/7f00b174-3efa-479a-a374-f508fa2230d9)

**To Reproduce**

On the Steam 2013 version, with FFNx, with default `enable_ffmpeg_videos = -1` or `enable_ffmpeg_videos = 1` the game fails to use the FMVs with the file name 'disc-1_00h.avi' (PC2000 file names)

On the PC 2000 version, with FFNx, with `enable_ffmpeg_videos = 1` the game fails to use the FMVs with the file name 'disc00_00h.avi' (Steam file names) with the exception of `disc04_00h.avi`

**Expected behavior**

- Would be nice to have a file name for the FMVs that works across both versions of the game with `enable_ffmpeg_videos = 1`
- And a `install folder\direct\movies` or `install folder\mods\movies` so I can avoid overriding people's OG FMVs during testing

**GPU (please complete the following information):**

- NVidia RTX 4070 Ti
- Driver Version 1.20.0.3

**Additional context**
You guys rock! thank you @julianxhokaxhiu and @myst6re !!!

**Comment by AxlRose-RX** [comment]
I forgot to mention that:

https://ff7-mods.github.io/ff7-flat-wiki/FF8/FileFormat_PAK.html

lists the FMV file names for the PC2000 inside the .pak files, the same as the Steam 2013 file names for the h (high res I think it means)

**Comment by myst6re** [comment]
I think this issue was fixed before, but the fix works only for the Steam version. I can make a Pull Request with the proper fix

**Comment by julianxhokaxhiu** [comment]
If you know already what to fix I'd appreciate that. Otherwise I can try to unpack this one and see what I find. Let me know, thank you

**Comment by myst6re** [comment]
And it's done!

**Comment by julianxhokaxhiu** [comment]
@AxlRose-RX for the second request, you can make use of the [`override_path`](https://github.com/julianxhokaxhiu/FFNx/blob/master/misc/FFNx.toml#L489-L491) which was made to fill exactly that gap. Feel free to test it.

**Comment by AxlRose-RX** [comment]
> @AxlRose-RX for the second request, you can make use of the [`override_path`](https://github.com/julianxhokaxhiu/FFNx/blob/master/misc/FFNx.toml#L489-L491) which was made to fill exactly that gap. Feel free to test it.

The first request, worked, FMVs are loading now with the right names on PC2000

`override_path = "axl"`
doesn't work on PC2000

added a folder:
C:\Square\FF8\axl\movies

and at the same time:
C:\Square\FF8\axl\Data\movies
