### ISSUE TITLE
[ FF7 ] Externally set music ids in config.toml does not play on certain enemy formations using FFNx v1.20.0.0 and later

### ISSUE THREAD

**Issue by silentC-VV** [julianxhokaxhiu/FFNx#738]
**Describe the bug:**
It seems on FFNx v1.20.0.0 and above (as of this writing), external modded music files set to run using config.toml in the mod's external music path does not seem to play the set music file on certain battles.  Perplexingly, only certain battles do not load the new music files while other battles still play correctly.  Also, this bug **does not occur** on FFNx v1.19.1.0 down to v1.18.1.0 which is the last I tested.  On the other hand, I have tested all public builds that are newer than those and the bug is present.

In the .IRO mod that I'm using, new music ids are set via mod.xml and new music is set to play using the specific enemy formation id and the shuffle function. Here's an example of what one looks like in config.toml:

```
[bat_644]
shuffle = [ 'demongates' ]
```
In this case "bat_644" refers to FF7's enemy formation id 644 which is the Demon Gates boss fight and the 'demongates' id is a new referenced file that is set and linked in mod.xml.

**To Reproduce:**
1. Install .iro music mod in 7th Heaven v3.5.1.0 or above.  The latest version of 7th Heaven does not seem to affect the bug even though v4.0.0.0 is a major update which has changes in music folder detection and ff7_en.exe wrapper injection.
3. Install FFNx v1.20.x.x
4. Open modded FF7 in 7th Heaven
5. Load a save that can head to the Demon Gates boss fight in the Forest Temple
6. Battle the Demon Gates boss

**Expected Behavior:**
Since this specific battle is set in the mod to play a different music file, it should play the new file rather than the generic boss fight theme.  The music plays correctly on previous versions of FFNx.

**Actual Behavior:**
On FFNx v1.20.x.x, instead of the specified new music track, it only plays the original boss theme which is the music ID "chu".  Since the music mod also changes the file referenced in "chu",  the track that plays is the modded version of "chu".

Additional context:
I have not tested this bug extensively but the problem occurs in different battles as well.  I have tested and confirmed on my end that the bug occurs in the Turks battle in Gongaga [bat_539], and Turks battle in Sector 8 tunnel [bat_840].  However, the new music still works on other battles like the Midgar Zolom [bat_469] and [bat_470].  And to reiterate again, the music bug does not occur in v1.19.1.0 prior.

EDIT:  I have a suspicion that its the battles loaded while in an interior field through in-game scripting and random battles in-field that are problematic.  It seems world map random battles and encounters like the Midgar Zolom can get their music replaced with no problems.

Here is a link to the music mod:  https://drive.google.com/file/d/1teW9B7wHrsW769ZTYAekO-Md49y18EuK/view?usp=drive_link

If anyone needs a FF7 PC save file which can go to certain battles quickly, just ask me I'll upload one.

GPU:
- NVIDIA RTX 3070
- Driver Version 561.09

**Comment by julianxhokaxhiu** [comment]
Please enable `trace_music` and attach the `FFNx.log` once you did run your test case, so I can have a better look. Thank you

**Comment by julianxhokaxhiu** [comment]
Can you please provide a save file and how to repro it so I can quickly test the fix? Thank you in advance

**Comment by julianxhokaxhiu** [comment]
Thanks for sharing them, however your link says I'm unauthorised. Can you please upload them here as a zip file using the upload function of Github?

**Comment by julianxhokaxhiu** [comment]
Feel free to try the latest canary, should be working fine now. Thanks a lot for reporting this bug :) Appreciated
