### ISSUE TITLE
[ FF8 ] Regession with blending type 2 in external textures

### ISSUE THREAD

**Issue by myst6re** [julianxhokaxhiu/FFNx#746]
## Describe the bug

Since FFNx 1.20.x, blending type 2 (substractive) does not work on external textures.

## To Reproduce
Use any existing mods using the Tonberry layer for field and go to the BGU elevator.

## Expected behavior
See https://github.com/julianxhokaxhiu/FFNx/issues/693

## Additional context
Before 1.20.x, the Tonberry layer was emulated via the TexturePacker (CPU side), the built texture was with alpha=127.
For some reason the GPU driver needs textures to have alpha=127 for blending type 4 to work.

**Comment by myst6re** [comment]
Two options to fix this bug:
- revert the change made in 1.20.0 and emulate the Tonberry compatibility layer on CPU side. Textures will be slower to load
- find why textures need to have alpha=127, and patch FFNx to remove this prerequisite

**Comment by julianxhokaxhiu** [comment]
As far as I am aware that value comes from the game engine, as we inherit whatever is being sent to use and we compute it against `255.0` so might be something deep in the game to find out.

However this might be a good starting point to investigate in case:
https://github.com/julianxhokaxhiu/FFNx/blob/master/src/common.cpp#L2206-L2224

I'll see if I find more.

**Comment by myst6re** [comment]
Maybe not related, I found the patch you've made long time ago to enable alpha on the elevator: https://github.com/julianxhokaxhiu/FFNx/commit/3315ebe7bf7eda51bc7af4edfb102fa9c1284904

**Comment by myst6re** [comment]
Maybe not related, I found the patch you've made long time ago to enable alpha (not the correct formula) on the elevator: https://github.com/julianxhokaxhiu/FFNx/commit/3315ebe7bf7eda51bc7af4edfb102fa9c1284904

Edit: I have a lot of GEQUAL with alpharef=112 in the elevator field.

**Comment by julianxhokaxhiu** [comment]
I think I might start to understand what is going, great finding.

Modulate Alpha actually does this in the shader code ( https://github.com/julianxhokaxhiu/FFNx/blob/master/misc/FFNx.frag#L274-L279 ) which simply multiplies the color by the pixel color value. Disabling it simply picks Alpha as it is, which might explain why I got it working back then as alpha didn't had to be "multiplied" by the vertex color when drawing the door texture, but simply inherited.

Not sure if this intel helps, but might help us on crack this specific issue.

**Comment by myst6re** [comment]
It seems that enabling modulate alpha fixes our issue with mods and do not change anything without mods. Can you confirm?

**Comment by julianxhokaxhiu** [comment]
The code changed a lot since then, maybe we fixed it at the source until that commit, so I trust your testing. I'm fine reverting that patch ( or merging your PR if you want to open one ). Let me know and thanks :)
