### ISSUE TITLE
[FF7] Game crashes on close, on latest canary

### ISSUE THREAD

**Issue by chrcoluk** [julianxhokaxhiu/FFNx#78]
The issue does not occur on 1.7.2.30 a previous canary build as well as builds before that.  Have not tested on builds in between.

Canary build 1.7.2.59
Windows 8.1 64bit
Nvidia 1080ti GPU
Tested with default ffnx.cfg no adjustments.  Tested with opengl renderer as well.

Either alt-f4 or clicking the close icon, the game crashes, so not a clean close, nothing is logged to the ffnx.log.

**Comment by julianxhokaxhiu** [comment]
Thanks for letting me know but I'm not able to replicate. Did you run the attached `ffnx.reg` file once before running the game?

**Comment by chrcoluk** [comment]
yeah, I ran the reg, and the driver is been used, I see the version, name etc. all in the titlebar.

When i said nothing is logged, I meant no errors are logged after the game is shutdown, sorry for the confusion, the log has the normal stuff in there.

**Comment by julianxhokaxhiu** [comment]
Sure, no worries! The thing is that others users are testing this very same scenario and it's not crashing for them. Although we're all on Windows 10, so it may be something on Windows 8.1, which unfortunately I do not own. I'll try to create a VM and check if I'm able to replicate this.

Feel free to hop on Discord for a faster troubleshooting in case :) I'll let you know ASAP how the test did end here.

**Comment by julianxhokaxhiu** [comment]
If you still have issues with it I do suggest to update the VCRedist files to the latest version ( see https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads ) as FFNx does in fact use the latest UCRT release on each build.

Cheers!

**Comment by julianxhokaxhiu** [comment]
This was definitely fixed with https://github.com/julianxhokaxhiu/FFNx/commit/ee7c057d883faccdd9e10757b28d5580754712dc

Latest canaries should no more be affected.
