### ISSUE TITLE
[ FF8 ] Alt+Tab or Windows key is prevented while running the game in Window mode

### ISSUE THREAD

**Issue by julianxhokaxhiu** [julianxhokaxhiu/FFNx#79]
It seems that the native WindowProc on FF8 blocks any key and not only the ones required by the game to be used. This includes also Alt+Tab or the Windows key, not allowing in fact the user to switch the focus of the app.

Initially reported by @shikulja

**Comment by julianxhokaxhiu** [comment]
After a lot of investigation and thanks to @Extapathy help, we have a workaround for this issue: Simply rename `FF8.exe` to `FF8_EN.exe` ( or whatever name you prefer ).

The root cause is an entry in the [Application Compatibility Database](https://docs.microsoft.com/en-us/windows/win32/devnotes/application-compatibility-database) which forcefully sets [IgnoreAltTab](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-7/cc722093(v=ws.10)?redirectedfrom=MSDN) for the FF8 process, which blocks Alt+Tab combination, Windows key and much more.

An investigation for a real fix is ongoing.

**Comment by julianxhokaxhiu** [comment]
Unfortunately it seems that WIndows provides no programmatic way to "disable" specific Application Shims which are forced through the Application Compatibility Database.

There is although a documented way to do so, for people who are not willing to rename their EXE file: [How To disable a compatibility fix within a database](https://docs.microsoft.com/en-us/windows/deployment/planning/enabling-and-disabling-compatibility-fixes-in-compatibility-administrator#disabling-compatibility-fixes)

![image](https://user-images.githubusercontent.com/1237070/86778872-2c89b280-c05b-11ea-8d95-d2a0b1e7a9b7.png)

It is **really important** to do this through the **32-bit** version ( and not the 64-bit one! ) as FF8 is a 32-bit application.

Because of this the issue will now be considered an external fix, unless a proper programmatic way will be discovered or documented by Microsoft.

**Comment by barkermn01** [comment]
That application will probably just be setting a Registry Key, so it would be a case of work out the registry key.

**Comment by julianxhokaxhiu** [comment]
Hi @barkermn01 thanks for the hint but we've already done that using https://docs.microsoft.com/en-us/sysinternals/downloads/procmon and there's no registry key involved.

This compatibility database is a file located in your file system, precisely C:\Windows\AppPatch and the record are stored inside of a binary file, which can be edited only through that GUI interface.

Although if you manage to find a way to "programmatically" instruct this Windows layer, to disable exactly that record, without requiring Administrative access, I'll be more than happy to implement it.

Thank you still for your time :)

**Comment by barkermn01** [comment]
So just been doing some reason on it and it's a compile XML file, https://www.geoffchappell.com/studies/windows/win32/apphelp/sdb/shimdbdc.htm

So it could be decompiled and re-compiled but I would say that would be part of an optional setup, E.G disable/enable window shim that asks for admin permissions, and otherwise just carries on

**Comment by Extapathy** [comment]
We can create shims, the main issue is that you can only seem to turn on fixes (you can't explicitly turn fixes off) and the shim doesn't seem to override the disable alt tab fix from the system database.

**Comment by barkermn01** [comment]
@Extapathy no riskier than altering a game's files, or live memory edits of another application's memory space, so long as it's an explicit option and not forcefully done it should be fine

**Comment by julianxhokaxhiu** [comment]
@barkermn01 I would prefer using workarounds that have an impact on the game, rather than on the overall environment where it runs :) But yeah, having such a "methodology", even better via Win32 APIs, is really appreciated. If anyone finds how to accomplish that, I'll be more than happy to help in implementing it.
