### ISSUE TITLE
[ FF7 ] MIDI not being played if use_external_music is false

### ISSUE THREAD

**Issue by unab0mb** [julianxhokaxhiu/FFNx#80]
If music/vgmstream exists (which it will for 7h mods), even if empty, then FFNx still attempts to play back OGG or there is no music playback when use_external_music = no. I either have to delete the music/vgmstream folder structure, or I have to set use_external_music = no AND external_music_path = some non-existent folder in the config to get MIDI playback.

I would think expected behavior is use_external_music = no would force ignoring external_music_path completely and go straight to MIDI playback.

**Comment by julianxhokaxhiu** [comment]
The driver will now check if the path contains files, and enable the flag only if that is true. This means that if you start the game without any mod ( and you set the flag to false ) you will get MIDI music.

Thanks for the report :)
