### ISSUE TITLE
[ FF8 ] Vibration support

### ISSUE THREAD

**Issue by julianxhokaxhiu** [julianxhokaxhiu/FFNx#81]
This topic has been a hot potato across various communities and forums. It seems that the game does not simply provide a vibration functionality OOB.

But...the engine on the other hand, it seems it has all the wires connected to actually do the vibration ( aka Force Feedback, talking in Direct Input language ).

In order to trigger it, the engine loads two files: `icon.sp1` and `vibration.vib`. While both files seems to be there inside of the `menu.fs` file, they seems to be actually zeroed/non-valid.

The function at `0x4A29A0` seems to be the one which is triggered everytime the controller is supposed to vibrate ( GF summons, Gunblade trigger, etc. ), although it does not because at a certain point it checks for a value in a struct, which it happens to be the `vibrate.vib` file in memory. As this file is mostly zeroed, the game thinks there's no vibration and so it moves on.

If we manage to pull out this file from the PSX release, there's a good chance we could get the vibration functionality back and/or implement only the missing bits to actually vibrate the controller.

**Comment by myst6re** [comment]
In fact `vibrate.vib` is fine, the game just does not implement directinput support for vibration. Most of the code is still here, except for few zeroed subs.

I made a pull request to activate vibrations on xinput devices, this works fine on battle. I also reenabled the old pause menu from the PSX version, with a vibration on/off option, this menu will appear on field or worldmap, only if a compatible gamepad is plugged.
