### ISSUE TITLE
[ FF7 ] No Encounter toggle

### ISSUE THREAD

**Issue by berserkingyadis** [julianxhokaxhiu/FFNx#87]
Since the Steam/PC version of FF7 does not have:

1. Speed-up functionality
2. No random encounters

It would be nice if this project enables them for the players. The speed-up already is in the dev-builds so that leaves the No-random encounter functionality.

The "No-random-encounters" booster is on PS4 FF7 and gets toggled via L3+R3, maybe that can be adapted here.

No that sure about the state of FF8, I think the steam version has both of these features but the "non-steam" version doesnt.

**Comment by julianxhokaxhiu** [comment]
Implemented as of the latest canary :) Enjoy!

See https://github.com/julianxhokaxhiu/FFNx#battle-mode-toggle
