### ISSUE TITLE
[FF7] Music starting "two" times

### ISSUE THREAD

**Issue by daedrixxx2** [julianxhokaxhiu/FFNx#88]
I've noticed while getting a Game Over that the music (over2.ogg) starts two times: it plays the first few seconds while still in battle mode, then fading to the Game Over screen it resets and starts again.
The same thing happens with "yufi.ogg" when recruiting Yuffie (not counting another music bug, which plays the music of the last field you've visited, and can be "fixed" saving on the world map and reloading the save, then the correct music will play). The music starts for two seconds, then stops for another two and restarts again.

EDIT: I've fixed the correct music not starting when recruiting Yuffie, now it starts immediatly and perfectly, and also the timing for the music in the Nibelheim Reactor scene in Cloud's mind, which is now synched with the PSX version, by editing flevel.lgp with Makou Reactor.
The "Game Over" bug still remains though. A similar bug (I think) happens when failing the Fort Condor minigame, defeating the enemy commander in battle, and re-entering the shack. The music starts, mutes for a sec, then continues.

**Comment by julianxhokaxhiu** [comment]
@daedrixxx2 can you please try again if you're still able to reproduce this issue? As you remember we got a long way since you opened it on the Audio Engine. Let me know therefore, if the issue does still persist :) Thank you!

**Comment by daedrixxx2** [comment]
I can confirm that by canary .176 this issue has been fixed and can be closed.

As you know, there are still some audio adjustments to be made to the fading out of the music in certain cutscenes, and some sfx audio bugs to be dealt with, which I'm sure will be fixed in due time.

I've noticed that in the latest build you've made it so that the music volume goes down when there are text boxes, surely to allow for the voice dub. Could you add an option in the config. so that one can chose wether to turn it on or off? Thanks again :)

**Comment by julianxhokaxhiu** [comment]
Ah yes, fair point. If there's no voice dubbing mod installed, that feature makes no sense. I'll add a flag for that behavior :)

Cheers!
