### ISSUE TITLE
[FF7] Weird black outlines around the characters' eyes and mouth in the world map.

### ISSUE THREAD

**Issue by daedrixxx2** [julianxhokaxhiu/FFNx#89]
Weird black outlines around the characters' eyes and mouth in the world map.
It didn't happen in the last stable release

**Comment by julianxhokaxhiu** [comment]
Hi @daedrixxx2 can you please attach some screenshot to check what's the issue? Can you also please test it in vanilla ( no external mods ) and check if it happens there too?

Thank you in advance.

**Comment by daedrixxx2** [comment]
![Immagine](https://user-images.githubusercontent.com/61243321/92245636-f0d96080-eec4-11ea-803b-eb063c8af11a.png)
Hi, thanks for the answer. This is what I was talking about.
I thought it could've been related to upscaling (I've set mine to x4, with x8 AA) but setting it to x2 only accentuates the problem.
My only mods are the upscaled backgrounds and FFXn for the music engine improvements, everything else is vanilla.
Without FFNx (latest canary) the bug doesn't occur

**Comment by julianxhokaxhiu** [comment]
Thanks for the reply. Can you please upload your `FFNx.cfg` file and your `FFNx.log` file?

**Comment by daedrixxx2** [comment]
[FFNx.log](https://github.com/julianxhokaxhiu/FFNx/files/5175214/FFNx.log)

Sure.

Sorry for the noob question, how can I upload FFNx.cfg? It's not supported it says.

**Comment by julianxhokaxhiu** [comment]
Could you try to set `linear_filter = no` and try again?

**Comment by daedrixxx2** [comment]
Done. No change.

**Comment by julianxhokaxhiu** [comment]
Allright, thanks :) I'll check that later then.

**Comment by julianxhokaxhiu** [comment]
I did try to debug this case using the latest canary and your very same settings, but using the vanilla game.

This is the result:
![image](https://user-images.githubusercontent.com/1237070/92329090-80b61080-f065-11ea-8dc9-8ffeedf33313.png)

I suppose the issue you're facing has to do with some texture packs you're using. Can you please let me know which one you're using?

**Comment by daedrixxx2** [comment]
Mmmhhh... weird. I'm using FF7 SYW "ArkTsukiVock" (v4) upscale, (mods/Textures) in .dds format, for fields, world map, battle and minigames. But I don't think it should touch the characters's model on the world map.

**Comment by julianxhokaxhiu** [comment]
@satsukiyatoshi  would you be able to check if you can reproduce the issue?

**Comment by satsukiyatoshi** [comment]
I'll check this evening then report here

**Comment by satsukiyatoshi** [comment]
No problem here:
![Screen Shot 018](https://user-images.githubusercontent.com/8547498/92331795-756ce000-f079-11ea-9854-aef4e6ee3fa3.PNG)

My config (rendering parts):
renderer_backend = 0
internal_resolution_scale = 4
fancy_transparency = yes
enable_antialiasing = 8
preserve_aspect = yes
fullscreen = no
window_size_x = 1600
window_size_y = 900
enable_vsync = yes
refresh_rate = 60
enable_anisotropic = yes
linear_filter = no

@daedrixxx2
could you try in you cfg file to change:
renderer_backend = 1 to renderer_backend = 0
linear_filter = no (no use with HQ background you'll only get smother rendering, it's eating up texture details)
fancy_transparency = no to fancy_transparency = yes (>probably this is the culprist if renderer_backend is not)

**Comment by daedrixxx2** [comment]
> fancy_transparency = no to fancy_transparency = yes (>probably this is the culprist if renderer_backend is not)

That was it! Strange, as in the last stable release (1.7.0) that setting was set to default (no) and I didn't get the bug.
Actually, the main use of the linear filter for me is to smooth the Buster Sword background in the main menu XD

Anyway, thank you both for helping me out :)
